// The CI gate (RFC 0009): CI runs peer-ai check on every change, so work is held to its record
// without anyone having to remember to set that up. On GitHub Actions, render writes a workflow of
// its own for it, owned the way the security workflow is: rewritten while it's as render left it,
// and left alone once someone changes it by hand. For any other CI, render prints the step to add.
// peer-ai doctor warns while nothing runs it, so the AI tool hears about it in every session.

import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import type { PeerAiConfig } from "peer-ai-workflow";
import { type Check, ok, skip, warn } from "./checks.ts";
import { detectDelivery } from "./detect.ts";
import { VERSION } from "./package-info.ts";
import { CHECKOUT, SETUP_NODE, WORKFLOW_FILE, sameFile, unchangedSinceRender, withHash } from "./pipeline.ts";

export const GATE_FILE = ".github/workflows/peer-ai.yml";
const WORKFLOWS = ".github/workflows";
/** Workflows Peer AI writes for itself, which on their own aren't a project's CI. */
const OWN = [GATE_FILE, WORKFLOW_FILE, `${WORKFLOWS}/copilot-setup-steps.yml`];
/** A command that runs the gate: peer-ai check, with or without a version. */
const GATE_COMMAND = /\bpeer-ai(@\S+)?\s+check\b/;

/** Whether a CI file runs the gate: a line with the command, not a comment or a job's name. */
const runsGate = (text: string): boolean =>
  text.split(/\r?\n/).some((line) => !/^\s*#/.test(line) && !/^\s*-?\s*name:/.test(line) && GATE_COMMAND.test(line));

/** The gate's command, with the exact version render runs as, so CI needs no package.json. */
export const gateCommand = (): string => `npx -y peer-ai@${VERSION} check`;

const read = (root: string, path: string): string | undefined => {
  const full = join(root, path);
  return existsSync(full) && statSync(full).isFile() ? readFileSync(full, "utf8") : undefined;
};

/** The files of a pipeline: a folder's YAML files, or the file itself. */
function filesOf(root: string, pipeline: string): string[] {
  if (!pipeline.endsWith("/")) return [pipeline];
  const dir = join(root, pipeline);
  if (!existsSync(dir) || !statSync(dir).isDirectory()) return [];
  return readdirSync(dir)
    .filter((name) => /\.ya?ml$/.test(name))
    .sort()
    .map((name) => `${pipeline}${name}`);
}

/** The workflow render writes for the gate: Node 24 and the exact version, so any project can run it. */
export function gateWorkflow(config: PeerAiConfig): string {
  const branch = config.repo?.defaultBranch;
  // A verify taken from CI is confirmed with GitHub through gh, which needs the run's token and
  // permission to read checks (RFC 0013).
  const confirmsCi = config.commands?.verifyCheck !== undefined;
  const body = [
    "name: Peer AI",
    "on:",
    "  pull_request:",
    // With no default branch in the config, changes are checked in their pull requests.
    ...(branch === undefined ? [] : ["  push:", `    branches: [${branch}]`]),
    "permissions:",
    "  contents: read",
    ...(confirmsCi ? ["  checks: read"] : []),
    "jobs:",
    "  peer-ai-check:",
    "    name: peer-ai check",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 10",
    "    steps:",
    `      - uses: ${CHECKOUT}`,
    "        with:",
    // The pull request's own commit, with its history, so the commits each record names are there.
    "          ref: ${{ github.event.pull_request.head.sha || github.sha }}",
    "          fetch-depth: 0",
    "          persist-credentials: false",
    `      - uses: ${SETUP_NODE}`,
    "        with:",
    "          node-version: 24",
    `      - run: ${gateCommand()}`,
    ...(confirmsCi ? ["        env:", "          GH_TOKEN: ${{ github.token }}"] : []),
    "",
  ].join("\n");
  return withHash(
    [
      "# Generated by peer-ai render from peer-ai.config.json: the gate, peer-ai check (RFC 0009).",
      "# Change the config, not this file. Render writes it again while it's as render left it, and leaves",
      "# it alone once someone changes it by hand. Make the job a required check: its name never changes.",
    ],
    body,
  );
}

export interface Gate {
  /** What render does to the gate's workflow, on GitHub Actions. */
  planned?: { path: string; action: "create" | "update" | "unchanged" | "kept"; content?: string; note?: string };
  /** The step to add by hand, for any other CI. */
  manual?: string;
  /** Where the gate runs already, when it does. */
  runsIn?: string;
}

/** Whether the project's CI is GitHub Actions: workflows of its own, or the gate render wrote. */
export function onGitHubActions(root: string): boolean {
  return read(root, GATE_FILE) !== undefined || filesOf(root, `${WORKFLOWS}/`).some((path) => !OWN.includes(path));
}

/** Where the gate stands, and what render does about it. */
export function planGate(root: string, config: PeerAiConfig): Gate {
  if (config.delivery?.gate === false) return {};
  const existing = read(root, GATE_FILE);
  const others = filesOf(root, `${WORKFLOWS}/`).filter((path) => path !== GATE_FILE);
  const onActions = onGitHubActions(root) || (config.delivery?.pipeline ?? "").startsWith(WORKFLOWS);
  if (onActions) {
    if (existing === undefined) {
      // A gate someone added to a workflow of their own is enough: there is never a second one.
      const elsewhere = others.find((path) => runsGate(read(root, path) ?? ""));
      if (elsewhere !== undefined) return { runsIn: elsewhere };
      return { planned: { path: GATE_FILE, action: "create", content: gateWorkflow(config) } };
    }
    if (unchangedSinceRender(existing)) {
      const content = gateWorkflow(config);
      const same = sameFile(existing, content);
      return {
        planned: { path: GATE_FILE, action: same ? "unchanged" : "update", ...(same ? {} : { content }) },
        runsIn: GATE_FILE,
      };
    }
    return {
      planned: {
        path: GATE_FILE,
        action: "kept",
        note: "It was changed by hand, so keeping it up to date is yours now; peer-ai doctor checks it still runs peer-ai check. Delete it to have render write Peer AI's again.",
      },
      ...(runsGate(existing) ? { runsIn: GATE_FILE } : {}),
    };
  }
  const pipeline =
    detectDelivery(root)?.pipeline ?? (config.delivery?.ci === "existing" ? config.delivery.pipeline : undefined);
  // A workflows folder that holds only Peer AI's own files isn't the project's CI.
  if (pipeline === undefined || pipeline.startsWith(WORKFLOWS)) return {};
  const runs = filesOf(root, pipeline).find((path) => runsGate(read(root, path) ?? ""));
  if (runs !== undefined) return { runsIn: runs };
  return {
    manual: `Your CI, ${pipeline}, doesn't run Peer AI's gate. Add a step that runs, with Node 24, after the project's own checks: ${gateCommand()}`,
  };
}

const NOT_GATED = "No CI runs peer-ai check, so nothing holds work to its record in CI.";

/**
 * peer-ai doctor's check: CI runs the gate, unless the config turns it off. With no CI yet there is
 * nothing to say; the delivery check reports that already.
 */
export function checkGate(root: string, config: PeerAiConfig): Check[] {
  if (config.delivery?.gate === false) return [skip("gate", "The CI gate is off: delivery.gate is false.")];
  const gate = planGate(root, config);
  const action = gate.planned?.action;
  if (action === "create") return [warn("gate", NOT_GATED, `Run npx peer-ai render. It writes ${GATE_FILE}.`)];
  if (action === "update") return [warn("gate", `${GATE_FILE} is out of date.`, "Run npx peer-ai render.")];
  if (action === "kept" && gate.runsIn === undefined) {
    return [
      warn(
        "gate",
        `${GATE_FILE} was changed by hand, and no longer runs peer-ai check.`,
        `Put the step back: - run: ${gateCommand()}`,
      ),
    ];
  }
  if (gate.runsIn !== undefined) return [ok("gate", `CI runs peer-ai check: ${gate.runsIn}`)];
  if (gate.manual !== undefined) return [warn("gate", NOT_GATED, gate.manual)];
  return [];
}
