import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { loadConfig } from "./assess.ts";
import { main } from "./cli.ts";
import { VERSION } from "./package-info.ts";
import { END, START, instructions, planRender, runRender, serverCommand } from "./render.ts";
import { capture, cleanUp, project } from "./test-helpers.ts";

afterEach(cleanUp);

const json = (value: unknown) => JSON.stringify(value);
const ALL_TOOLS = ["claude-code", "codex", "cursor", "copilot", "gemini-cli"];

const config = (extra: Record<string, unknown> = {}) =>
  json({
    version: 1,
    project: { name: "Shop", stage: "mvp" },
    tools: ALL_TOOLS,
    tracks: [{ id: "web", kind: "web", path: "apps/web", status: "active" }],
    ...extra,
  });

const read = (root: string, path: string) => readFileSync(join(root, path), "utf8");
const render = (root: string, check = false) => {
  const out = capture();
  const code = runRender({ cwd: root, check }, out);
  return { code, text: out.text() };
};
const SERVER = { command: "npx", args: ["-y", `peer-ai@${VERSION}`, "mcp"] };

describe("render", () => {
  it("sets up every tool in the config, and changes nothing on a second run", () => {
    const root = project({ "peer-ai.config.json": config() });
    const first = render(root);
    expect(first.code).toBe(0);
    for (const path of [
      "AGENTS.md",
      "CLAUDE.md",
      ".mcp.json",
      ".cursor/rules/peer-ai.mdc",
      ".cursor/mcp.json",
      ".github/copilot-instructions.md",
      ".vscode/mcp.json",
      "GEMINI.md",
      ".gemini/settings.json",
    ]) {
      expect(first.text).toContain(`✓ ${path} created.`);
    }
    expect(first.text).toContain(`codex mcp add peer-ai -- npx -y peer-ai@${VERSION} mcp`);
    expect(JSON.parse(read(root, ".mcp.json"))).toEqual({ mcpServers: { "peer-ai": SERVER } });
    expect(JSON.parse(read(root, ".vscode/mcp.json"))).toEqual({
      servers: { "peer-ai": { type: "stdio", ...SERVER } },
    });
    expect(read(root, ".cursor/rules/peer-ai.mdc")).toMatch(/^---\ndescription: .+\nalwaysApply: true\n---\n/);
    expect(read(root, "AGENTS.md")).toMatch(new RegExp(`^${START}\\n<!-- Generated by peer-ai render`));

    const second = render(root);
    expect(second.text).not.toMatch(/created|updated/);
    expect(render(root, true).code).toBe(0);
  });

  it("rewrites only its own block, and --check notices when the block is out of date", () => {
    const root = project({
      "peer-ai.config.json": config({ tools: ["claude-code"] }),
      "CLAUDE.md": "# House rules\n\nUse tabs.",
    });
    render(root);
    expect(read(root, "CLAUDE.md")).toMatch(new RegExp(`^# House rules\\n\\nUse tabs\\.\\n\\n${START}\\n`));
    writeFileSync(join(root, "CLAUDE.md"), `${read(root, "CLAUDE.md")}\n## Notes\n\nKeep this.\n`);
    writeFileSync(
      join(root, "peer-ai.config.json"),
      config({ tools: ["claude-code"], project: { name: "Shop", stage: "production" } }),
    );

    const stale = render(root, true);
    expect(stale.code).toBe(1);
    expect(stale.text).toContain("✗ CLAUDE.md is out of date.");
    expect(read(root, "CLAUDE.md")).toContain("at the mvp stage");

    render(root);
    const rendered = read(root, "CLAUDE.md");
    expect(rendered).toContain("at the production stage");
    expect(rendered).toMatch(/^# House rules\n\nUse tabs\.\n\n/);
    expect(rendered).toMatch(/\n## Notes\n\nKeep this\.\n$/);
    expect(rendered.split(START)).toHaveLength(2);
  });

  it("leaves a CLAUDE.md that imports AGENTS.md alone, and writes AGENTS.md instead", () => {
    const root = project({ "peer-ai.config.json": config({ tools: ["claude-code"] }), "CLAUDE.md": "@AGENTS.md\n" });
    expect(render(root).text).toContain(
      "✓ CLAUDE.md is up to date. It imports AGENTS.md, which carries the instructions.",
    );
    expect(read(root, "CLAUDE.md")).toBe("@AGENTS.md\n");
    expect(read(root, "AGENTS.md")).toContain(START);
  });

  it("doesn't create AGENTS.md for a project that only uses Claude Code", () => {
    const root = project({ "peer-ai.config.json": config({ tools: ["claude-code"] }) });
    render(root);
    expect(existsSync(join(root, "AGENTS.md"))).toBe(false);
    expect(read(root, "CLAUDE.md")).toContain(START);
  });

  it("keeps other MCP servers and settings, and refuses what it can't safely edit", () => {
    const root = project({
      "peer-ai.config.json": config({ tools: ["claude-code", "copilot", "gemini-cli"] }),
      ".mcp.json": json({ mcpServers: { database: { command: "db-mcp" } } }),
      ".gemini/settings.json": json({ theme: "dark" }),
      ".vscode/mcp.json": '{\n  // our servers\n  "servers": {}\n}\n',
      "GEMINI.md": `# Notes\n\n${START}\nhalf a block\n`,
    });
    const { code, text } = render(root);
    expect(code).toBe(1);
    expect(JSON.parse(read(root, ".mcp.json"))).toEqual({
      mcpServers: { database: { command: "db-mcp" }, "peer-ai": SERVER },
    });
    expect(JSON.parse(read(root, ".gemini/settings.json"))).toEqual({
      theme: "dark",
      mcpServers: { "peer-ai": SERVER },
    });
    expect(read(root, ".vscode/mcp.json")).toContain("// our servers");
    expect(text).toContain("✗ .vscode/mcp.json wasn't changed.");
    expect(text).toContain(`add this under "servers" by hand: "peer-ai": ${json({ type: "stdio", ...SERVER })}`);
    expect(text).toContain("✗ GEMINI.md wasn't changed.");
    expect(text).toContain(`It has ${START} but no ${END} after it.`);
  });

  it("starts the server from the project's pinned copy when it has one", () => {
    expect(serverCommand(project())).toEqual(SERVER);
    const pinned = project({ "package.json": json({ devDependencies: { "peer-ai": "1.0.0" } }) });
    expect(serverCommand(pinned)).toEqual({ command: "npx", args: ["peer-ai", "mcp"] });
  });

  it("writes only AGENTS.md when no tools are listed, and says so", () => {
    const root = project({ "peer-ai.config.json": config({ tools: undefined }) });
    const { code, text } = render(root);
    expect(code).toBe(0);
    const { config: loaded } = loadConfig(root);
    if (loaded === undefined) throw new Error("the test config is not valid");
    expect(planRender(root, loaded).files.map((file) => file.path)).toEqual(["AGENTS.md"]);
    expect(text).toContain("No AI tools are listed in peer-ai.config.json, so only AGENTS.md was written.");
  });

  it("needs a valid config, and runs from the command line", async () => {
    expect(render(project()).code).toBe(2);
    const root = project({ "peer-ai.config.json": config({ tools: ["cursor"] }) });
    expect(await main(["render", "--check"], { cwd: root, out: capture() })).toBe(1);
    expect(await main(["render"], { cwd: root, out: capture() })).toBe(0);
    expect(await main(["render", "--check"], { cwd: root, out: capture() })).toBe(0);
  });
});

describe("the instructions", () => {
  it("tell the agent how to work, and describe the project briefly", () => {
    const root = project({
      "peer-ai.config.json": config({
        tracks: [
          { id: "web", kind: "web", path: "apps/web", status: "active" },
          { id: "billing", kind: "backend", repo: "acme/billing", status: "external" },
        ],
        commands: { verify: null, test: "make test", lint: "make lint" },
        compliance: { jurisdictions: ["NG", "GB"], packs: ["ndpa", "uk-gdpr"] },
        rules: [{ path: "CONTEXT.md", description: "Repository rules" }],
      }),
    });
    const { config: loaded } = loadConfig(root);
    if (loaded === undefined) throw new Error("the test config is not valid");
    const text = instructions(loaded);
    expect(text).toContain("Start each session with `next_work`.");
    expect(text).toContain("- `web` (web, active): apps/web\n- `billing` (backend, external): in acme/billing");
    expect(text).toContain("Commands: test `make test`, lint `make lint`.");
    expect(text).toContain("Compliance for NG, GB: ndpa, uk-gdpr.");
    expect(text).toContain("- `CONTEXT.md`: Repository rules");
    expect(text.split("\n").length).toBeLessThan(40);
  });
});
