import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { availableSkills } from "peer-ai-skills";
import type { ToolId } from "peer-ai-workflow";
import { afterEach, describe, expect, it } from "vitest";
import { loadConfig } from "./assess.ts";
import { main } from "./cli.ts";
import { VERSION } from "./package-info.ts";
import { END, START, instructions, planRender, runRender, serverCommand, skillFolders } from "./render.ts";
import { capture, cleanUp, project } from "./test-helpers.ts";

afterEach(cleanUp);

const json = (value: unknown) => JSON.stringify(value);
const ALL_TOOLS = ["claude-code", "codex", "cursor", "copilot", "gemini-cli"];

const config = (extra: Record<string, unknown> = {}) =>
  json({
    version: 1,
    project: { name: "Shop", stage: "mvp" },
    tools: ALL_TOOLS,
    tracks: [{ id: "web", kind: "web", path: "apps/web", status: "active" }],
    ...extra,
  });

const ALL_SKILLS = availableSkills()
  .map((id) => `peer-ai-${id}`)
  .join(", ");
const read = (root: string, path: string) => readFileSync(join(root, path), "utf8");
const render = (root: string, check = false) => {
  const out = capture();
  const code = runRender({ cwd: root, check }, out);
  return { code, text: out.text() };
};
const SERVER = { command: "npx", args: ["-y", `peer-ai@${VERSION}`, "mcp"] };

describe("render", () => {
  it("sets up every tool in the config, and changes nothing on a second run", () => {
    const root = project({ "peer-ai.config.json": config() });
    const first = render(root);
    expect(first.code).toBe(0);
    for (const path of [
      "AGENTS.md",
      "CLAUDE.md",
      ".mcp.json",
      ".cursor/rules/peer-ai.mdc",
      ".cursor/mcp.json",
      ".github/copilot-instructions.md",
      ".vscode/mcp.json",
      "GEMINI.md",
      ".gemini/settings.json",
    ]) {
      expect(first.text).toContain(`✓ ${path} created.`);
    }
    expect(first.text).toContain(`codex mcp add peer-ai -- npx -y peer-ai@${VERSION} mcp`);
    expect(first.text).toContain('[mcp_servers.peer-ai.tools.run_verify] approval_mode = "approve"');
    expect(JSON.parse(read(root, ".mcp.json"))).toEqual({ mcpServers: { "peer-ai": SERVER } });
    expect(JSON.parse(read(root, ".vscode/mcp.json"))).toEqual({
      servers: { "peer-ai": { type: "stdio", ...SERVER } },
    });
    expect(read(root, ".cursor/rules/peer-ai.mdc")).toMatch(/^---\ndescription: .+\nalwaysApply: true\n---\n/);
    expect(read(root, "AGENTS.md")).toMatch(new RegExp(`^${START}\\n<!-- Generated by peer-ai render`));
    expect(read(root, "CLAUDE.md")).toBe("@AGENTS.md\n");
    expect(read(root, "GEMINI.md")).toBe("@AGENTS.md\n");

    const second = render(root);
    expect(second.text).not.toMatch(/created|updated/);
    expect(render(root, true).code).toBe(0);
  });

  it("rewrites only its own block, and --check notices when the block is out of date", () => {
    const root = project({
      "peer-ai.config.json": config({ tools: ["claude-code"] }),
      "CLAUDE.md": "# House rules\n\nUse tabs.",
    });
    render(root);
    expect(read(root, "CLAUDE.md")).toMatch(new RegExp(`^# House rules\\n\\nUse tabs\\.\\n\\n${START}\\n`));
    writeFileSync(join(root, "CLAUDE.md"), `${read(root, "CLAUDE.md")}\n## Notes\n\nKeep this.\n`);
    writeFileSync(
      join(root, "peer-ai.config.json"),
      config({ tools: ["claude-code"], project: { name: "Shop", stage: "production" } }),
    );

    const stale = render(root, true);
    expect(stale.code).toBe(1);
    expect(stale.text).toContain("✗ CLAUDE.md is out of date.");
    expect(read(root, "CLAUDE.md")).toContain("at the mvp stage");

    render(root);
    const rendered = read(root, "CLAUDE.md");
    expect(rendered).toContain("at the production stage");
    expect(rendered).toMatch(/^# House rules\n\nUse tabs\.\n\n/);
    expect(rendered).toMatch(/\n## Notes\n\nKeep this\.\n$/);
    expect(rendered.split(START)).toHaveLength(2);
  });

  it("leaves a CLAUDE.md that imports AGENTS.md alone, and writes AGENTS.md instead", () => {
    const root = project({ "peer-ai.config.json": config({ tools: ["claude-code"] }), "CLAUDE.md": "@AGENTS.md\n" });
    expect(render(root).text).toContain(
      "✓ CLAUDE.md is up to date. It imports AGENTS.md, which carries the instructions.",
    );
    expect(read(root, "CLAUDE.md")).toBe("@AGENTS.md\n");
    expect(read(root, "AGENTS.md")).toContain(START);
  });

  it("doesn't create AGENTS.md for a project that only uses Claude Code", () => {
    const root = project({ "peer-ai.config.json": config({ tools: ["claude-code"] }) });
    render(root);
    expect(existsSync(join(root, "AGENTS.md"))).toBe(false);
    expect(read(root, "CLAUDE.md")).toContain(START);
  });

  it("keeps other MCP servers and settings, and refuses what it can't safely edit", () => {
    const root = project({
      "peer-ai.config.json": config({ tools: ["claude-code", "copilot", "gemini-cli"] }),
      ".mcp.json": json({ mcpServers: { database: { command: "db-mcp" } } }),
      ".gemini/settings.json": json({ theme: "dark" }),
      ".vscode/mcp.json": '{\n  // our servers\n  "servers": {}\n}\n',
      "GEMINI.md": `# Notes\n\n${START}\nhalf a block\n`,
    });
    const { code, text } = render(root);
    expect(code).toBe(1);
    expect(JSON.parse(read(root, ".mcp.json"))).toEqual({
      mcpServers: { database: { command: "db-mcp" }, "peer-ai": SERVER },
    });
    expect(JSON.parse(read(root, ".gemini/settings.json"))).toEqual({
      theme: "dark",
      mcpServers: { "peer-ai": SERVER },
    });
    expect(read(root, ".vscode/mcp.json")).toContain("// our servers");
    expect(text).toContain("✗ .vscode/mcp.json wasn't changed.");
    expect(text).toContain(`add this under "servers" by hand: "peer-ai": ${json({ type: "stdio", ...SERVER })}`);
    expect(text).toContain("✗ GEMINI.md wasn't changed.");
    expect(text).toContain(`It has ${START} but no ${END} after it.`);
  });

  it("writes Ruff's settings for the project's Python profiles, and --check notices when they fall behind", () => {
    const python = (overrides: Record<string, unknown> = {}) =>
      config({
        tools: ["codex"],
        tracks: [{ id: "api", kind: "backend", path: "services/api", status: "active", stack: ["python", "fastapi"] }],
        standards: { profiles: ["python-fastapi"], overrides },
      });
    const root = project({ "peer-ai.config.json": python() });
    render(root);
    const ruff = read(root, ".peer-ai/enforce/ruff.toml");
    expect(ruff).toContain('extend-select = [ "ANN001", "ANN401", "BLE001", "E722"');
    expect(ruff).toContain("[lint.pylint]\nmax-statements = 50");
    expect(render(root, true).code).toBe(0);
    writeFileSync(
      join(root, "peer-ai.config.json"),
      python({ "PY-10": { value: 70, reason: "Report builders run long" } }),
    );
    expect(render(root, true).code).toBe(1);
    render(root);
    expect(read(root, ".peer-ai/enforce/ruff.toml")).toContain("max-statements = 70");
  });

  it("writes the pipeline's workflow, and leaves it alone once someone changes it by hand", () => {
    const pipeline = config({
      tools: ["codex"],
      repo: { host: "github" },
      standards: { profiles: ["github-actions"] },
    });
    const root = project({ "peer-ai.config.json": pipeline });
    render(root);
    const path = ".github/workflows/peer-ai-security.yml";
    expect(read(root, path)).toContain("  secrets:\n");
    expect(render(root, true).code).toBe(0);
    writeFileSync(join(root, path), read(root, path).replace("ubuntu-latest", "ubuntu-24.04"));
    const kept = render(root);
    expect(kept.code).toBe(0);
    expect(kept.text).toContain("left as it is. It was changed by hand");
    expect(read(root, path)).toContain("ubuntu-24.04");
    expect(render(root, true).code).toBe(0);
  });

  it("starts the server from the project's pinned copy when it has one", () => {
    expect(serverCommand(project())).toEqual(SERVER);
    const pinned = project({ "package.json": json({ devDependencies: { "peer-ai": "1.0.0" } }) });
    expect(serverCommand(pinned)).toEqual({ command: "npx", args: ["peer-ai", "mcp"] });
  });

  it.each<[string[], string[]]>([
    [["claude-code"], [".claude/skills"]],
    [["codex"], [".agents/skills"]],
    [["gemini-cli"], [".agents/skills"]],
    [["cursor"], [".agents/skills"]],
    [["claude-code", "cursor", "copilot"], [".claude/skills"]],
    [
      ["claude-code", "codex"],
      [".claude/skills", ".agents/skills"],
    ],
    [[], []],
  ])("writes skills for %j where those tools read them: %j", (tools, folders) => {
    expect(skillFolders(tools as ToolId[])).toEqual(folders);
  });

  it("writes each skill under a peer-ai- name, keeps it out of git, and rebuilds only what changed", () => {
    const root = project({
      "peer-ai.config.json": config({ tools: ["claude-code", "codex"] }),
      ".gitignore": "node_modules/\n",
      ".claude/skills/team-release/SKILL.md": "---\nname: team-release\n---\n",
    });
    const first = render(root);
    expect(first.code).toBe(0);
    for (const home of [".claude/skills", ".agents/skills"]) {
      expect(read(root, `${home}/peer-ai-security-review/SKILL.md`)).toMatch(/^---\nname: peer-ai-security-review\n/);
      expect(existsSync(join(root, `${home}/peer-ai-security-review/references/rules.md`))).toBe(true);
      expect(first.text).toContain(`✓ ${home}/: written ${ALL_SKILLS}.`);
    }
    expect(read(root, ".gitignore")).toBe(
      "node_modules/\n\n# peer-ai:start\n# Generated by peer-ai render. Peer AI's skills are rebuilt from the installed version: run peer-ai render after cloning.\n/.claude/skills/peer-ai-*/\n/.agents/skills/peer-ai-*/\n# Feedback drafts stay on this machine until a person sends them.\n/.peer-ai/feedback/\n# peer-ai:end\n",
    );
    expect(first.text).toContain("The skills stay out of git: run peer-ai render after cloning.");
    expect(read(root, ".claude/skills/team-release/SKILL.md")).toBe("---\nname: team-release\n---\n");

    expect(render(root).text).toContain(`✓ .claude/skills/: ${String(availableSkills().length)} skills, up to date.`);
    writeFileSync(join(root, ".claude/skills/peer-ai-security-review/SKILL.md"), "edited by hand");
    writeFileSync(join(root, ".claude/skills/peer-ai-security-review/notes.md"), "left over");
    // CI never has the skills, so --check leaves them out; doctor reports them locally.
    expect(render(root, true)).toMatchObject({
      code: 0,
      text: expect.stringContaining("Everything is up to date.") as unknown,
    });
    const { config: loaded } = loadConfig(root);
    if (loaded === undefined) throw new Error("the test config is not valid");
    const { skills } = planRender(root, loaded);
    expect(skills.find((skill) => skill.path === ".claude/skills/peer-ai-security-review")).toMatchObject({
      action: "update",
      stale: ["notes.md"],
    });
    render(root);
    expect(read(root, ".claude/skills/peer-ai-security-review/SKILL.md")).toMatch(
      /^---\nname: peer-ai-security-review\n/,
    );
    expect(existsSync(join(root, ".claude/skills/peer-ai-security-review/notes.md"))).toBe(false);
  });

  it("removes Peer AI skills this version doesn't have, and those no listed tool reads", () => {
    const root = project({
      "peer-ai.config.json": config({ tools: ["claude-code"] }),
      ".claude/skills/peer-ai-retired-skill/SKILL.md": "old",
      ".agents/skills/peer-ai-security-review/SKILL.md": "old",
    });
    const { text } = render(root);
    expect(text).toContain(`✓ .claude/skills/: written ${ALL_SKILLS}; removed peer-ai-retired-skill.`);
    expect(text).toContain("✓ .agents/skills/: removed peer-ai-security-review.");
    expect(existsSync(join(root, ".claude/skills/peer-ai-retired-skill"))).toBe(false);
    expect(existsSync(join(root, ".agents/skills/peer-ai-security-review"))).toBe(false);
  });

  it("sets up each cloud agent to write the skills before it starts", () => {
    const command = `npx -y peer-ai@${VERSION} render --skills --quiet`;
    const root = project({ "peer-ai.config.json": config() });
    const { text } = render(root);
    expect(JSON.parse(read(root, ".claude/settings.json"))).toEqual({
      hooks: { SessionStart: [{ matcher: "startup", hooks: [{ type: "command", command }] }] },
    });
    expect(JSON.parse(read(root, ".cursor/environment.json"))).toEqual({ start: command });
    const workflow = read(root, ".github/workflows/copilot-setup-steps.yml");
    expect(workflow).toContain("jobs:\n  copilot-setup-steps:\n    runs-on: ubuntu-latest\n");
    expect(workflow).toContain(`      - run: ${command}\n`);
    expect(workflow).toMatch(/uses: actions\/checkout@[0-9a-f]{40} #/);
    expect(text).toContain(`Codex cloud keeps its setup script in the environment's settings`);
    expect(text).toContain(command);
    expect(render(root).text).toContain("✓ .claude/settings.json is up to date.");
  });

  it("adds to setup files that already exist, updates its own command, and refuses what it can't edit", () => {
    const old = "npx -y peer-ai@0.0.1 render --skills --quiet";
    const root = project({
      "peer-ai.config.json": config({ tools: ["claude-code", "cursor", "copilot"] }),
      ".claude/settings.json": json({
        permissions: { allow: ["Bash(npm test)"] },
        hooks: {
          SessionStart: [
            { hooks: [{ type: "command", command: "echo hello" }] },
            { hooks: [{ type: "command", command: old }] },
          ],
        },
      }),
      ".cursor/environment.json": json({ install: "npm ci", start: "sudo service docker start" }),
      ".github/workflows/copilot-setup-steps.yml": "jobs:\n  copilot-setup-steps:\n    steps:\n      - run: npm ci\n",
    });
    const { code, text } = render(root);
    const command = `npx -y peer-ai@${VERSION} render --skills --quiet`;
    const settings = JSON.parse(read(root, ".claude/settings.json")) as Record<string, unknown>;
    expect(settings).toEqual({
      permissions: { allow: ["Bash(npm test)"] },
      hooks: {
        SessionStart: [
          { hooks: [{ type: "command", command: "echo hello" }] },
          { hooks: [{ type: "command", command }] },
        ],
      },
    });
    expect(JSON.parse(read(root, ".cursor/environment.json"))).toEqual({
      install: "npm ci",
      start: `sudo service docker start && ${command}`,
    });
    expect(code).toBe(1);
    expect(text).toContain("✗ .github/workflows/copilot-setup-steps.yml wasn't changed.");
    expect(text).toContain(`add this step to its copilot-setup-steps job: - run: ${command}`);
  });

  it("writes only the skills, quietly, for a setup step", () => {
    const root = project({ "peer-ai.config.json": config({ tools: ["claude-code"] }) });
    const out = capture();
    expect(runRender({ cwd: root, check: false, skills: true, quiet: true }, out)).toBe(0);
    expect(out.text()).toBe("");
    expect(existsSync(join(root, ".claude/skills/peer-ai-security-review/SKILL.md"))).toBe(true);
    expect(existsSync(join(root, "CLAUDE.md"))).toBe(false);
    expect(existsSync(join(root, ".gitignore"))).toBe(false);
  });

  it("commits the skills when the project asks, marking them as generated", () => {
    const root = project({
      "peer-ai.config.json": config({ tools: ["claude-code"], skills: { commit: true } }),
      ".gitignore": "node_modules/\n\n# peer-ai:start\n/.claude/skills/peer-ai-*/\n# peer-ai:end\n",
    });
    const { text } = render(root);
    // Committed skills leave the block, and feedback drafts still stay out of git.
    expect(read(root, ".gitignore")).toBe(
      "node_modules/\n\n# peer-ai:start\n# Generated by peer-ai render.\n# Feedback drafts stay on this machine until a person sends them.\n/.peer-ai/feedback/\n# peer-ai:end\n",
    );
    expect(read(root, ".gitattributes")).toContain("/.claude/skills/peer-ai-*/** linguist-generated=true");
    expect(text).toContain("Done. Commit these files, so every clone and every tool gets them.");
    expect(text).not.toContain("The skills stay out of git");
    writeFileSync(join(root, ".claude/skills/peer-ai-security-review/SKILL.md"), "edited");
    const checked = render(root, true);
    expect(checked.code).toBe(1);
    expect(checked.text).toContain("✗ .claude/skills/peer-ai-security-review/ is out of date.");
  });

  it("writes only AGENTS.md when no tools are listed, and says so", () => {
    const root = project({ "peer-ai.config.json": config({ tools: undefined }) });
    const { code, text } = render(root);
    expect(code).toBe(0);
    const { config: loaded } = loadConfig(root);
    if (loaded === undefined) throw new Error("the test config is not valid");
    expect(planRender(root, loaded).files.map((file) => file.path)).toEqual(["AGENTS.md", ".gitignore"]);
    expect(text).toContain(
      "No AI tools are listed in peer-ai.config.json, so AGENTS.md is the only instructions file written.",
    );
  });

  it("needs a valid config, and runs from the command line", async () => {
    expect(render(project()).code).toBe(2);
    const root = project({ "peer-ai.config.json": config({ tools: ["cursor"] }) });
    expect(await main(["render", "--check"], { cwd: root, out: capture() })).toBe(1);
    expect(await main(["render"], { cwd: root, out: capture() })).toBe(0);
    expect(await main(["render", "--check"], { cwd: root, out: capture() })).toBe(0);
  });
});

describe("the instructions", () => {
  it("tell the agent how to work, and describe the project briefly", () => {
    const root = project({
      "peer-ai.config.json": config({
        tracks: [
          { id: "web", kind: "web", path: "apps/web", status: "active" },
          { id: "billing", kind: "backend", repo: "acme/billing", status: "external" },
        ],
        commands: { verify: null, test: "make test", lint: "make lint" },
        compliance: { jurisdictions: ["NG", "GB"], packs: ["ndpa", "uk-gdpr"] },
        rules: [{ path: "CONTEXT.md", description: "Repository rules" }],
      }),
    });
    const { config: loaded } = loadConfig(root);
    if (loaded === undefined) throw new Error("the test config is not valid");
    const text = instructions(loaded);
    expect(text).toContain("Start each session with `next_work`.");
    expect(text).toContain("`build` before you change code");
    expect(text).toContain("`done` once it is merged or released");
    expect(text).toContain("- `web` (web, active): apps/web\n- `billing` (backend, external): in acme/billing");
    expect(text).toContain("Commands: test `make test`, lint `make lint`.");
    expect(text).toContain("Compliance for NG, GB: ndpa, uk-gdpr.");
    expect(text).toContain("- `CONTEXT.md`: Repository rules");
    expect(text).not.toContain("Models:");
    expect(text).not.toContain("the project's settings");
    expect(text).not.toContain("When a work item reaches");
    expect(text.split("\n").length).toBeLessThan(40);
  });

  function instructionsFor(extra: Record<string, unknown>): string {
    const root = project({ "peer-ai.config.json": config(extra) });
    const { config: loaded, errors } = loadConfig(root);
    if (loaded === undefined) throw new Error(`the test config is not valid: ${(errors ?? []).join("; ")}`);
    return instructions(loaded);
  }

  it("name the pinned models, and what to do when one isn't offered", () => {
    const pinned = instructionsFor({
      models: { policy: "pinned", default: "model-a", byActivity: { build: "model-b", verify: "model-c" } },
    });
    expect(pinned).toContain(
      "Models: model-a by default; build: model-b; verify: model-c. If one isn't offered, use the most capable one available. Never run a review on a weaker model than the build.",
    );
    const ask = instructionsFor({ models: { policy: "pinned", default: "model-a", ifUnavailable: "ask" } });
    expect(ask).toContain("Models: model-a by default. If one isn't offered, ask the person which to use.");
    expect(instructionsFor({ models: { policy: "tiers" } })).toContain(
      "Models: never run a review on a weaker model than the build.",
    );
    expect(instructionsFor({ models: { policy: "none" } })).not.toContain("Models:");
  });

  it("pass each skill's add-ons, checklists and notes to the AI tool", () => {
    const text = instructionsFor({
      capabilities: {
        "code-review": { also: ["engineering:code-review", "/code-review"], notes: ["Quote\n  the line."] },
        "security-review": { checklists: ["docs/checklists/payments.md", "docs/checklists/uploads.md"] },
      },
    });
    expect(text).toContain(
      "When you use one of Peer AI's skills, follow the project's settings for it. If an add-on it names isn't available, tell the person; never skip it silently.",
    );
    expect(text).toContain("- `peer-ai-code-review`: also use `engineering:code-review` and `/code-review`.");
    expect(text).toContain("- For `peer-ai-code-review`: Quote the line.");
    expect(text).toContain(
      "- `peer-ai-security-review` also checks against `docs/checklists/payments.md` and `docs/checklists/uploads.md`.",
    );
  });

  it("only mention add-ons when a skill has some", () => {
    const text = instructionsFor({ capabilities: { architecture: { notes: ["Keep the modules as they are."] } } });
    expect(text).toContain("When you use one of Peer AI's skills, follow the project's settings for it.\n");
    expect(text).not.toContain("never skip it silently");
    expect(text).toContain("- For `peer-ai-architecture`: Keep the modules as they are.");
  });

  it("pass each activity's inputs and notes to the AI tool", () => {
    const text = instructionsFor({
      activities: {
        specify: { inputs: ["docs/design/brief.md"], notes: ["Every screen has a way back from a mistake."] },
        build: { notes: ["Work one ticket at a time.", "Push after each commit."] },
      },
    });
    expect(text).toContain(
      [
        "When a work item reaches one of these activities:",
        "",
        "- Before `specify`, read `docs/design/brief.md`.",
        "- During `specify`: Every screen has a way back from a mistake.",
        "- During `build`: Work one ticket at a time.",
        "- During `build`: Push after each commit.",
      ].join("\n"),
    );
  });
});
