// peer-ai render: writes what each AI tool in the config reads, so every tool works the project
// the same way. Instructions go in a marked block inside the project's own files (AGENTS.md,
// CLAUDE.md, GEMINI.md, Copilot's instructions), and only that block is ever rewritten. Cursor gets
// a rule file of its own. The MCP server is registered in each tool's project config, next to
// whatever else is there. Peer AI's skills are written where each tool reads them, under a peer-ai-
// prefix, and left out of git: they're rebuilt from the installed version (RFC 0004). So that cloud
// agents, which start from a fresh clone, have them too, each tool's setup step runs
// `peer-ai render --skills` before the agent starts. Running it twice changes nothing, and --check
// reports drift for CI.

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { SKILL_NAME_PREFIX, availableSkills, loadSkill, readSkillFiles, renderedName } from "peer-ai-skills";
import { ACTIVITY_IDS, SKILL_IDS, type PeerAiConfig, type ToolId } from "peer-ai-workflow";
import { loadConfig } from "./assess.ts";
import { count, fail, formatChecks, ok, plural, skip, type Check } from "./checks.ts";
import { CONFIG_FILE } from "./detect.ts";
import { FEEDBACK_DIR, FEEDBACK_REPO } from "./feedback.ts";
import type { Output } from "./init.ts";
import { VERSION } from "./package-info.ts";
import { planGate } from "./gate.ts";
import {
  CHECKOUT,
  SETUP_NODE,
  WORKFLOW_FILE,
  sameFile,
  unchangedSinceRender,
  workflowFile,
  workflowSummary,
} from "./pipeline.ts";
import { RUFF_FILE, ruffFile } from "./ruff.ts";
import { enforcementFor } from "./stages.ts";
import { renderedVersion } from "./versions.ts";

export const START = "<!-- peer-ai:start -->";
export const END = "<!-- peer-ai:end -->";
const GENERATED = `<!-- Generated by peer-ai render from ${CONFIG_FILE}. Change the config and run peer-ai render; edits inside this block are replaced. -->`;
const SERVER = "peer-ai";
const IMPORTS_AGENTS = /^@AGENTS\.md\s*$/m;

/** What render does to one file. `content` is the whole file to write, when it changes. */
export interface Planned {
  path: string;
  /** kept: a file render owns that someone changed by hand, which render leaves alone on purpose. */
  action: "create" | "update" | "unchanged" | "refused" | "kept";
  content?: string;
  note?: string;
}

/** What render does to one skill's folder. */
export interface PlannedSkill {
  /** The folder, such as .claude/skills/peer-ai-security-review. */
  path: string;
  action: "create" | "update" | "unchanged" | "remove";
  /** Every file the folder should hold, by its path inside the folder. */
  files: Map<string, string>;
  /** Files in the folder that shouldn't be there any more. */
  stale: string[];
}

export interface RenderPlan {
  files: Planned[];
  skills: PlannedSkill[];
  /** Steps render can't take inside the project, such as a tool that keeps servers in the user's own config. */
  manual: string[];
}

/** How AI tools start the server: the project's own pinned copy, or this exact version. */
export function serverCommand(root: string): { command: string; args: string[] } {
  const pkg = readJson(join(root, "package.json")) as
    { dependencies?: Record<string, string>; devDependencies?: Record<string, string> } | undefined;
  const pinned = pkg?.devDependencies?.["peer-ai"] ?? pkg?.dependencies?.["peer-ai"];
  return pinned === undefined
    ? { command: "npx", args: ["-y", `peer-ai@${VERSION}`, "mcp"] }
    : { command: "npx", args: ["peer-ai", "mcp"] };
}

/**
 * The command that writes only the skills, for a session or a cloud agent to run before it starts.
 * It uses the same peer-ai the MCP server does: the project's pinned copy, or this exact version.
 */
export function skillsCommand(root: string): string {
  const { command, args } = serverCommand(root);
  return [command, ...args.slice(0, -1), "render", "--skills", "--quiet"].join(" ");
}

/** Recognises the skills command in a setup file, whichever version it names. */
const SKILLS_COMMAND = /npx (?:-y )?peer-ai(?:@\S+)? render --skills(?: --quiet)?/;

function readJson(path: string): unknown {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return undefined;
  }
}

function readText(root: string, path: string): string | undefined {
  const full = join(root, path);
  return existsSync(full) ? readFileSync(full, "utf8") : undefined;
}

/** The instructions every tool gets: short, because the MCP server serves the detail on demand. */
export function instructions(config: PeerAiConfig): string {
  const { project } = config;
  const lines = [
    "## Peer AI",
    "",
    `This project uses Peer AI${project.stage === undefined ? "" : ` at the ${project.stage} stage`}. Its MCP server, \`${SERVER}\`, holds the project map, the work items, and the gates work must pass before it ships.`,
    "",
    "- Start each session with `next_work`. It returns the work item for the current branch and where it stopped. For new work, create one with `create_work_item`.",
    "- Keep the item's stage current with `advance_work_item`: `build` before you change code, `verify` once the change is complete, `ship` when it is verified, reviewed and ready to merge, and `done` once it is merged or released. When it refuses, fix what it lists.",
    "- Before editing a file, call `standards_for_file` and follow what it returns.",
    "- Record progress with `update_work_item`, so the next session resumes where this one stopped.",
    "- Verify with `run_verify`. Never report a verify result yourself. It verifies the item's latest commit, so commit first.",
    "- Working in a git worktree of your own, give your branch to `next_work`. The tools find each work item on its own branch, wherever it's checked out.",
    "- Peer AI's skills are named `peer-ai-…`, such as `peer-ai-security-review`. `next_work` names the one to use for a gap, and the reviews a work item needs; follow each skill step by step. If none are installed, run `npx peer-ai render --skills`.",
    "- For every review, write its report in `.peer-ai/reports/`, then record it with `record_review` and the report's path. Record failed and incomplete reviews too.",
    "- For every document a skill writes, such as the requirements, check it with `check_document` and fix what it names.",
    "- Don't edit the files in `.peer-ai/` by hand. The tools keep them valid.",
    "- When `next_work` reports setup problems, fix what you can, such as running `npx peer-ai render`, before other work, and tell the person in plain words about anything only they can decide.",
    "- When Peer AI gets something wrong, call `draft_feedback`. At a natural stopping point, show the person each draft in a few words and ask whether to send it.",
  ];
  const ownTracks = config.tracks.filter((track) => track.status !== "external");
  if (config.tracks.length > 1) {
    lines.push("", "Parts of the project:", "");
    for (const track of config.tracks) {
      const where =
        track.status === "external"
          ? `in ${track.repo ?? "another repository"}`
          : (track.path ?? "the repository root");
      lines.push(`- \`${track.id}\` (${track.kind}, ${track.status}): ${where}`);
    }
  } else if (ownTracks[0] !== undefined) {
    lines.push("", `The project is one ${ownTracks[0].kind} part, \`${ownTracks[0].id}\`.`);
  }
  const commands = Object.entries(config.commands ?? {}).filter(
    (entry): entry is [string, string] => typeof entry[1] === "string",
  );
  if (commands.length > 0) {
    lines.push("", `Commands: ${commands.map(([name, command]) => `${name} \`${command}\``).join(", ")}.`);
  }
  const compliance = config.compliance;
  const packs = [...(compliance?.packs ?? [])];
  if (packs.length + (compliance?.jurisdictions?.length ?? 0) > 0) {
    const where = compliance?.jurisdictions === undefined ? "" : ` for ${compliance.jurisdictions.join(", ")}`;
    lines.push("", `Compliance${where}: ${packs.length === 0 ? "rule packs to be chosen" : packs.join(", ")}.`);
  }
  if ((config.rules ?? []).length > 0) {
    lines.push("", "Every change respects the project's own rules:", "");
    for (const rule of config.rules ?? []) {
      lines.push(`- \`${rule.path}\`${rule.description === undefined ? "" : `: ${rule.description}`}`);
    }
  }
  lines.push(...projectSettings(config));
  lines.push("", "If the peer-ai tools aren't available, run `npx peer-ai doctor`.");
  return lines.join("\n");
}

const code = (text: string) => `\`${text}\``;

/** "a", "a and b", "a, b and c". */
function inWords(items: string[]): string {
  return items.length <= 1 ? items.join("") : `${items.slice(0, -1).join(", ")} and ${items.at(-1) ?? ""}`;
}

/** A note on one line, so it can't break the list it sits in. */
const oneLine = (note: string) => note.replace(/\s+/g, " ").trim();

// The project's own settings for models, skills and activities (RFC 0001), written where the AI
// tool reads them (RFC 0008). Only the keys a project sets produce a line.
function projectSettings(config: PeerAiConfig): string[] {
  const lines: string[] = [];
  const models = config.models;
  if (models?.policy === "pinned" && models.default !== undefined) {
    const byActivity = Object.entries(models.byActivity ?? {}).map(([activity, model]) => `${activity}: ${model}`);
    const unavailable =
      models.ifUnavailable === "ask"
        ? "If one isn't offered, ask the person which to use."
        : "If one isn't offered, use the most capable one available.";
    lines.push(
      "",
      `Models: ${[`${models.default} by default`, ...byActivity].join("; ")}. ${unavailable} Never run a review on a weaker model than the build.`,
    );
  } else if (models?.policy === "tiers") {
    lines.push("", "Models: never run a review on a weaker model than the build.");
  }

  const skills = SKILL_IDS.flatMap((skill) => {
    const capability = config.capabilities?.[skill];
    if (capability === undefined) return [];
    const name = code(renderedName(skill));
    return [
      ...((capability.also ?? []).length > 0
        ? [`- ${name}: also use ${inWords((capability.also ?? []).map(code))}.`]
        : []),
      ...((capability.checklists ?? []).length > 0
        ? [`- ${name} also checks against ${inWords((capability.checklists ?? []).map(code))}.`]
        : []),
      ...(capability.notes ?? []).map((note) => `- For ${name}: ${oneLine(note)}`),
    ];
  });
  if (skills.length > 0) {
    const addOns = SKILL_IDS.some((skill) => (config.capabilities?.[skill]?.also ?? []).length > 0);
    lines.push(
      "",
      `When you use one of Peer AI's skills, follow the project's settings for it.${addOns ? " If an add-on it names isn't available, tell the person; never skip it silently." : ""}`,
      "",
      ...skills,
    );
  }

  const activities = ACTIVITY_IDS.flatMap((activity) => {
    const settings = config.activities?.[activity];
    if (settings === undefined) return [];
    return [
      ...((settings.inputs ?? []).length > 0
        ? [`- Before ${code(activity)}, read ${inWords((settings.inputs ?? []).map(code))}.`]
        : []),
      ...(settings.notes ?? []).map((note) => `- During ${code(activity)}: ${oneLine(note)}`),
    ];
  });
  if (activities.length > 0) {
    lines.push("", "When a work item reaches one of these activities:", "", ...activities);
  }
  return lines;
}

const block = (body: string) => `${START}\n${GENERATED}\n\n${body}\n${END}`;

const IGNORE_START = "# peer-ai:start";
const IGNORE_END = "# peer-ai:end";

interface Markers {
  start: string;
  end: string;
  /** The whole block, markers included. */
  block: string;
}

/**
 * The file with its marked block written or replaced, and nothing outside the block touched. The
 * markers default to the instructions block; .gitignore uses its own.
 */
function withBlock(
  path: string,
  existing: string | undefined,
  body: string,
  markers: Markers = { start: START, end: END, block: block(body) },
): Planned {
  const wanted = markers.block;
  if (existing === undefined) return { path, action: "create", content: `${wanted}\n` };
  const from = existing.indexOf(markers.start);
  if (from === -1) {
    const separator = existing === "" ? "" : existing.endsWith("\n") ? "\n" : "\n\n";
    return { path, action: "update", content: `${existing}${separator}${wanted}\n` };
  }
  const to = existing.indexOf(markers.end, from);
  if (to === -1) {
    return {
      path,
      action: "refused",
      note: `It has ${markers.start} but no ${markers.end} after it. Add the end marker, or remove the start marker, then render again.`,
    };
  }
  const content = `${existing.slice(0, from)}${wanted}${existing.slice(to + markers.end.length)}`;
  return { path, action: content === existing ? "unchanged" : "update", content };
}

/** Registers the server under `key` in a JSON config, keeping every other entry as it is. */
function withServer(root: string, path: string, key: string, entry: Record<string, unknown>): Planned {
  const existing = readText(root, path);
  if (existing === undefined) {
    return { path, action: "create", content: `${JSON.stringify({ [key]: { [SERVER]: entry } }, null, 2)}\n` };
  }
  const parsed = readJson(join(root, path));
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    return {
      path,
      action: "refused",
      note: `It isn't plain JSON (comments aren't supported here), so add this under "${key}" by hand: "${SERVER}": ${JSON.stringify(entry)}`,
    };
  }
  const config = parsed as Record<string, unknown>;
  const servers = (typeof config[key] === "object" && config[key] !== null ? config[key] : {}) as Record<
    string,
    unknown
  >;
  if (JSON.stringify(servers[SERVER]) === JSON.stringify(entry)) return { path, action: "unchanged" };
  const content = `${JSON.stringify({ ...config, [key]: { ...servers, [SERVER]: entry } }, null, 2)}\n`;
  return { path, action: "update", content };
}

function cursorRule(body: string): string {
  return [
    "---",
    "description: How to work in this project with Peer AI",
    "alwaysApply: true",
    "---",
    "",
    GENERATED.replace("edits inside this block are replaced", "this file is replaced"),
    "",
    body,
    "",
  ].join("\n");
}

/**
 * A tool's own instructions file. When AGENTS.md carries the block, a new file just imports it, so
 * the tool doesn't read the instructions twice; an existing file that imports it is left alone.
 */
function toolFile(root: string, path: string, body: string, agentsRendered: boolean): Planned {
  const existing = readText(root, path);
  if (existing === undefined && agentsRendered) {
    return { path, action: "create", content: "@AGENTS.md\n", note: "It imports AGENTS.md." };
  }
  if (existing !== undefined && IMPORTS_AGENTS.test(existing) && !existing.includes(START)) {
    return { path, action: "unchanged", note: "It imports AGENTS.md, which carries the instructions." };
  }
  return withBlock(path, existing, body);
}

/**
 * Where the tools in the config read skills. Codex, Cursor, Copilot and Gemini CLI read the shared
 * .agents/skills; Claude Code reads .claude/skills, which Cursor and Copilot also read. So each
 * skill is written as few times as the tools allow, and not at all when no tool is listed.
 */
export function skillFolders(tools: ToolId[]): string[] {
  const folders = tools.includes("claude-code") ? [".claude/skills"] : [];
  const needsShared = tools.some((tool) => tool === "codex" || tool === "gemini-cli" || tool === "other");
  const readsEither = tools.some((tool) => tool === "cursor" || tool === "copilot");
  if (needsShared || (readsEither && folders.length === 0)) folders.push(".agents/skills");
  return folders;
}

const SKILL_HOMES = [".claude/skills", ".agents/skills"];

const isDirectory = (path: string) => statSync(path, { throwIfNoEntry: false })?.isDirectory() === true;

/**
 * Every Peer AI skill in each folder its tools read, and every Peer AI skill that shouldn't be
 * there any more: one this version no longer has, or one in a folder no listed tool reads.
 */
function planSkills(root: string, tools: ToolId[]): PlannedSkill[] {
  const folders = skillFolders(tools);
  const planned: PlannedSkill[] = [];
  for (const home of SKILL_HOMES) {
    const wanted = folders.includes(home) ? availableSkills() : [];
    for (const id of wanted) {
      const name = renderedName(id);
      const path = `${home}/${name}`;
      const files = loadSkill(id, { name });
      const existing = isDirectory(join(root, path)) ? readSkillFiles(join(root, path)) : undefined;
      const stale = existing === undefined ? [] : [...existing.keys()].filter((file) => !files.has(file));
      const same =
        existing !== undefined && stale.length === 0 && [...files].every(([file, text]) => existing.get(file) === text);
      planned.push({ path, action: existing === undefined ? "create" : same ? "unchanged" : "update", files, stale });
    }
    const names = new Set(wanted.map(renderedName));
    const present = isDirectory(join(root, home)) ? readdirSync(join(root, home)) : [];
    for (const entry of present.filter((entry) => entry.startsWith(SKILL_NAME_PREFIX) && !names.has(entry))) {
      planned.push({ path: `${home}/${entry}`, action: "remove", files: new Map(), stale: [] });
    }
  }
  return planned;
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

/** A JSON file changed by `change`, or refused when it isn't plain JSON, with what to add by hand. */
function editJson(
  root: string,
  path: string,
  create: Record<string, unknown>,
  change: (current: Record<string, unknown>) => Record<string, unknown>,
  byHand: string,
): Planned {
  const existing = readText(root, path);
  if (existing === undefined) return { path, action: "create", content: `${JSON.stringify(create, null, 2)}\n` };
  const parsed = readJson(join(root, path));
  if (!isRecord(parsed)) {
    return { path, action: "refused", note: `It isn't plain JSON (comments aren't supported here), so ${byHand}` };
  }
  const changed = change(parsed);
  if (JSON.stringify(changed) === JSON.stringify(parsed)) return { path, action: "unchanged" };
  return { path, action: "update", content: `${JSON.stringify(changed, null, 2)}\n` };
}

/**
 * Claude Code runs a project's SessionStart hooks in every session, including cloud sessions,
 * which start from a fresh clone. The hook writes the skills before the session begins.
 */
function claudeSessionHook(root: string, command: string): Planned {
  const hook = { type: "command", command };
  const entry = { matcher: "startup", hooks: [hook] };
  return editJson(
    root,
    ".claude/settings.json",
    { hooks: { SessionStart: [entry] } },
    (settings) => {
      const hooks = isRecord(settings.hooks) ? settings.hooks : {};
      const groups: unknown[] = Array.isArray(hooks.SessionStart) ? hooks.SessionStart : [];
      const isOurs = (item: unknown): item is Record<string, unknown> =>
        isRecord(item) && typeof item.command === "string" && SKILLS_COMMAND.test(item.command);
      const inGroup = (group: unknown): unknown[] => (isRecord(group) && Array.isArray(group.hooks) ? group.hooks : []);
      const found = groups.some((group) => inGroup(group).some(isOurs));
      const updated = groups.map((group) =>
        isRecord(group) && Array.isArray(group.hooks)
          ? { ...group, hooks: group.hooks.map((item: unknown) => (isOurs(item) ? { ...item, command } : item)) }
          : group,
      );
      return { ...settings, hooks: { ...hooks, SessionStart: found ? updated : [...groups, entry] } };
    },
    `add a SessionStart hook that runs: ${command}`,
  );
}

/** Cursor's cloud agents run the environment's start command each time an agent boots. */
function cursorEnvironment(root: string, command: string): Planned {
  return editJson(
    root,
    ".cursor/environment.json",
    { start: command },
    (environment) => {
      const start = typeof environment.start === "string" ? environment.start : undefined;
      const next =
        start === undefined || start === ""
          ? command
          : SKILLS_COMMAND.test(start)
            ? start.replace(SKILLS_COMMAND, command)
            : `${start} && ${command}`;
      return { ...environment, start: next };
    },
    `add to its "start" command: ${command}`,
  );
}

/**
 * Copilot's cloud agent runs the copilot-setup-steps job before it starts. A workflow that already
 * exists is left to its owner, with the step to add.
 */
function copilotSetupSteps(root: string, command: string): Planned {
  const path = ".github/workflows/copilot-setup-steps.yml";
  const existing = readText(root, path);
  if (existing !== undefined) {
    if (!SKILLS_COMMAND.test(existing)) {
      return {
        path,
        action: "refused",
        note: `It exists, so add this step to its copilot-setup-steps job: - run: ${command}`,
      };
    }
    const content = existing.replace(SKILLS_COMMAND, command);
    return { path, action: content === existing ? "unchanged" : "update", content };
  }
  const content = [
    "# Prepares Copilot's cloud agent before it starts. Peer AI's step writes its skills, which stay",
    "# out of git. Generated by peer-ai render; add your own steps after Peer AI's.",
    "name: Copilot setup steps",
    "on: workflow_dispatch",
    "permissions:",
    "  contents: read",
    "jobs:",
    "  copilot-setup-steps:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    `      - uses: ${CHECKOUT}`,
    `      - uses: ${SETUP_NODE}`,
    "        with:",
    "          node-version: 24",
    `      - run: ${command}`,
    "",
  ].join("\n");
  return { path, action: "create", content };
}

const ATTRIBUTES_START = "# peer-ai:start";
const ATTRIBUTES_END = "# peer-ai:end";

/** Committed skills are marked as generated, so pull requests fold them away. */
function markSkillsGenerated(root: string, folders: string[]): Planned {
  const lines = [
    ATTRIBUTES_START,
    "# Generated by peer-ai render: Peer AI's skills, rebuilt from the installed version.",
    ...folders.map((folder) => `/${folder}/${SKILL_NAME_PREFIX}*/** linguist-generated=true`),
    ATTRIBUTES_END,
  ];
  const markers = { start: ATTRIBUTES_START, end: ATTRIBUTES_END, block: lines.join("\n") };
  return withBlock(".gitattributes", readText(root, ".gitattributes"), "", markers);
}

/**
 * Keeps out of git, in a marked block of .gitignore, what never belongs there: the rendered skills,
 * unless the project commits them, and feedback drafts, which stay on the person's machine until
 * they send them (RFC 0007).
 */
function ignoreBlock(root: string, folders: string[]): Planned {
  const lines = [
    IGNORE_START,
    ...(folders.length === 0
      ? ["# Generated by peer-ai render."]
      : [
          "# Generated by peer-ai render. Peer AI's skills are rebuilt from the installed version: run peer-ai render after cloning.",
          ...folders.map((folder) => `/${folder}/${SKILL_NAME_PREFIX}*/`),
        ]),
    "# Feedback drafts stay on this machine until a person sends them.",
    `/${FEEDBACK_DIR}/`,
    IGNORE_END,
  ];
  const markers = { start: IGNORE_START, end: IGNORE_END, block: lines.join("\n") };
  return withBlock(".gitignore", readText(root, ".gitignore"), "", markers);
}

export function planRender(root: string, config: PeerAiConfig): RenderPlan {
  const tools: ToolId[] = config.tools ?? [];
  const body = instructions(config);
  const server = serverCommand(root);
  const files: Planned[] = [];
  const manual: string[] = [];
  const previous = renderedVersion(root);
  if (previous !== undefined && previous !== VERSION) {
    manual.push(
      `This moves the project from Peer AI ${previous} to ${VERSION}. What changed: https://github.com/${FEEDBACK_REPO}/releases/tag/v${VERSION}`,
    );
  }
  const uses = (tool: ToolId) => tools.includes(tool);
  const imports = (path: string) => IMPORTS_AGENTS.test(readText(root, path) ?? "");

  // AGENTS.md is the file most tools read. A project that only uses Claude Code gets it when it
  // already has one, or when CLAUDE.md or GEMINI.md imports it.
  const agents =
    tools.length === 0 ||
    tools.some((tool) => tool !== "claude-code") ||
    existsSync(join(root, "AGENTS.md")) ||
    imports("CLAUDE.md");
  if (agents) files.push(withBlock("AGENTS.md", readText(root, "AGENTS.md"), body));

  if (uses("claude-code")) {
    files.push(toolFile(root, "CLAUDE.md", body, agents));
    files.push(withServer(root, ".mcp.json", "mcpServers", server));
  }
  if (uses("cursor")) {
    const path = ".cursor/rules/peer-ai.mdc";
    const content = cursorRule(body);
    const existing = readText(root, path);
    files.push({
      path,
      action: existing === undefined ? "create" : existing === content ? "unchanged" : "update",
      content,
    });
    files.push(withServer(root, ".cursor/mcp.json", "mcpServers", server));
  }
  if (uses("copilot")) {
    files.push(withBlock(".github/copilot-instructions.md", readText(root, ".github/copilot-instructions.md"), body));
    files.push(withServer(root, ".vscode/mcp.json", "servers", { type: "stdio", ...server }));
  }
  if (uses("gemini-cli")) {
    files.push(toolFile(root, "GEMINI.md", body, agents));
    files.push(withServer(root, ".gemini/settings.json", "mcpServers", server));
  }
  const command = skillsCommand(root);
  // Ruff reads settings from a file, not a package, so its settings for the project's stack
  // profiles are written where the project's own Ruff settings can extend them (RFC 0006).
  // Where the project stands in adopting enforcement: reporting or enforcing, rules deferred, and
  // checks its own workflows already run (RFC 0011).
  const enforcement = enforcementFor(root, config);
  const ruff = ruffFile(config, enforcement);
  if (ruff !== undefined) {
    const existing = readText(root, RUFF_FILE);
    const action = existing === undefined ? "create" : existing === ruff ? "unchanged" : "update";
    files.push({
      path: RUFF_FILE,
      action,
      content: ruff,
      ...(action === "unchanged"
        ? {}
        : {
            note: "Ruff reads it only when your own Ruff settings extend it, and it adds rules without replacing yours.",
          }),
    });
  }

  // The pipeline profile's checks, as one workflow render owns while nobody changes it by hand.
  const workflow = workflowFile(config, enforcement);
  // Every security check render adds is named, with whether it blocks, so nothing arrives silently.
  const summary = workflowSummary(config, enforcement) ?? "";
  if (workflow !== undefined) {
    const existing = readText(root, WORKFLOW_FILE);
    if (existing === undefined) files.push({ path: WORKFLOW_FILE, action: "create", content: workflow, note: summary });
    else if (unchangedSinceRender(existing)) {
      const same = sameFile(existing, workflow);
      files.push({
        path: WORKFLOW_FILE,
        action: same ? "unchanged" : "update",
        ...(same ? {} : { content: workflow, note: summary }),
      });
    } else {
      files.push({
        path: WORKFLOW_FILE,
        action: "kept",
        note: "It was changed by hand, so keeping it up to date with the config is yours now; peer-ai doctor checks it still has every job. Delete it to have render write Peer AI's again.",
      });
    }
  }

  // The CI gate, peer-ai check (RFC 0009): a workflow of its own on GitHub Actions, a step to add elsewhere.
  const gate = planGate(root, config);
  if (gate.planned !== undefined) files.push(gate.planned);
  if (gate.manual !== undefined) manual.push(gate.manual);

  if (uses("claude-code")) files.push(claudeSessionHook(root, command));
  if (uses("cursor")) files.push(cursorEnvironment(root, command));
  if (uses("copilot")) files.push(copilotSetupSteps(root, command));
  if (uses("codex")) {
    manual.push(
      `Codex cloud keeps its setup script in the environment's settings, not the project. Add this line to it, so the skills and the MCP server are ready before the agent starts (its internet is off while it works): ${command}`,
    );
    manual.push(
      `Codex keeps MCP servers in your own config, not the project's. Register it once: codex mcp add ${SERVER} -- ${server.command} ${server.args.join(" ")}`,
      `Codex asks before run_verify, because it runs the project's verify command. To allow it without asking, add to ~/.codex/config.toml: [mcp_servers.${SERVER}.tools.run_verify] approval_mode = "approve"`,
    );
  }
  if (uses("other")) {
    manual.push(
      `For another tool, point it at AGENTS.md, and register the MCP server as: ${server.command} ${server.args.join(" ")}`,
    );
  }
  const skills = planSkills(root, tools);
  const folders = skillFolders(tools);
  const committed = config.skills?.commit === true;
  if (committed && folders.length > 0) files.push(markSkillsGenerated(root, folders));
  const ignoredSkills = committed || !skills.some((skill) => skill.action !== "remove") ? [] : folders;
  files.push(ignoreBlock(root, ignoredSkills));
  return { files, skills, manual };
}

function write(root: string, planned: Planned): void {
  if (planned.content === undefined) return;
  const full = join(root, planned.path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, planned.content);
}

function writeSkill(root: string, skill: PlannedSkill): void {
  const folder = join(root, skill.path);
  if (skill.action === "remove") {
    rmSync(folder, { recursive: true, force: true });
    return;
  }
  for (const file of skill.stale) unlinkSync(join(folder, file));
  for (const [file, text] of skill.files) {
    mkdirSync(dirname(join(folder, file)), { recursive: true });
    writeFileSync(join(folder, file), text);
  }
}

/** One line per skills folder, rather than one per file. */
function skillChecks(skills: PlannedSkill[]): Check[] {
  const homes = [...new Set(skills.map((skill) => skill.path.slice(0, skill.path.lastIndexOf("/"))))];
  return homes.map((home) => {
    const here = skills.filter((skill) => skill.path.startsWith(`${home}/`));
    const changed = here.filter((skill) => skill.action !== "unchanged");
    const names = (action: PlannedSkill["action"]) =>
      here.filter((skill) => skill.action === action).map((skill) => skill.path.slice(home.length + 1));
    if (changed.length === 0) return ok("render", `${home}/: ${plural(here.length, "skill")}, up to date.`);
    const parts = [
      ["written", [...names("create"), ...names("update")]],
      ["removed", names("remove")],
    ] as const;
    const summary = parts
      .filter(([, list]) => list.length > 0)
      .map(([verb, list]) => `${verb} ${list.join(", ")}`)
      .join("; ");
    return ok("render", `${home}/: ${summary}.`);
  });
}

function toCheck(planned: Planned, checking: boolean): Check {
  switch (planned.action) {
    case "refused":
      return fail("render", `${planned.path} wasn't changed.`, planned.note ?? "");
    case "kept":
      return skip("render", `${planned.path} left as it is. ${planned.note ?? ""}`.trim());
    case "unchanged":
      return ok("render", `${planned.path} is up to date.${planned.note === undefined ? "" : ` ${planned.note}`}`);
    default:
      return checking
        ? fail("render", `${planned.path} is out of date.`, "Run peer-ai render.")
        : ok(
            "render",
            `${planned.path} ${planned.action === "create" ? "created" : "updated"}.${planned.note === undefined ? "" : ` ${planned.note}`}`,
          );
  }
}

export interface RenderOptions {
  cwd: string;
  /** Change nothing; fail when a file is out of date. For CI. */
  check: boolean;
  /** Write only the skills, touching nothing that's committed. What each tool's setup step runs. */
  skills?: boolean;
  /** Print nothing unless something fails. */
  quiet?: boolean;
}

/** Exit code 0 when done or up to date; 1 when a file was refused, or out of date with --check; 2 without a valid config. */
export function runRender(options: RenderOptions, out: Output): number {
  const { config, errors } = loadConfig(options.cwd);
  if (config === undefined) {
    if (errors === undefined) out.error(`There is no ${CONFIG_FILE}. Run peer-ai init first.`);
    else {
      out.error(`${CONFIG_FILE} is not valid:`);
      for (const error of errors) out.error(`  ${error}`);
    }
    return 2;
  }
  const plan = planRender(options.cwd, config);
  if (options.skills === true) {
    for (const skill of plan.skills) if (skill.action !== "unchanged") writeSkill(options.cwd, skill);
    if (options.quiet !== true) for (const line of formatChecks(skillChecks(plan.skills))) out.log(line);
    return 0;
  }
  const committed = config.skills?.commit === true;
  if (!options.check) {
    for (const planned of plan.files)
      if (planned.action !== "refused" && planned.action !== "kept") write(options.cwd, planned);
    for (const skill of plan.skills) if (skill.action !== "unchanged") writeSkill(options.cwd, skill);
  }
  // --check is for CI, which sees only what's committed. Skills usually aren't, so it leaves them
  // out unless the project commits them; peer-ai doctor reports missing skills on a person's machine.
  const skillLines = !options.check
    ? skillChecks(plan.skills)
    : committed
      ? plan.skills
          .filter((skill) => skill.action !== "unchanged")
          .map((skill) => fail("render", `${skill.path}/ is out of date.`, "Run peer-ai render."))
      : [];
  const checks = [...plan.files.map((planned) => toCheck(planned, options.check)), ...skillLines];
  if ((config.tools ?? []).length === 0) {
    checks.push(
      skip("render", `No AI tools are listed in ${CONFIG_FILE}, so AGENTS.md is the only instructions file written.`),
    );
  }
  const failures = count(checks, "fail");
  if (options.quiet === true && failures === 0) return 0;
  out.log(`Peer AI render: ${config.project.name}`);
  out.log("");
  for (const line of formatChecks(checks)) out.log(line);
  for (const step of plan.manual) out.log(`  ! ${step}`);
  out.log("");
  if (options.check) out.log(failures === 0 ? "Everything is up to date." : "Out of date: run peer-ai render.");
  else if (failures > 0) out.log("Some files couldn't be changed; see above.");
  else if (!committed && plan.skills.some((skill) => skill.action !== "remove")) {
    out.log(
      "Done. Commit these files, so every clone and every tool gets them. The skills stay out of git: run peer-ai render after cloning.",
    );
  } else out.log("Done. Commit these files, so every clone and every tool gets them.");
  return failures === 0 ? 0 : 1;
}
