// peer-ai render: writes what each AI tool in the config reads, so every tool works the project
// the same way. Instructions go in a marked block inside the project's own files (AGENTS.md,
// CLAUDE.md, GEMINI.md, Copilot's instructions), and only that block is ever rewritten. Cursor gets
// a rule file of its own. The MCP server is registered in each tool's project config, next to
// whatever else is there. Running it twice changes nothing, and --check reports drift for CI.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { PeerAiConfig, ToolId } from "@peer-ai/workflow";
import { loadConfig } from "./assess.ts";
import { count, fail, formatChecks, ok, skip, type Check } from "./checks.ts";
import { CONFIG_FILE } from "./detect.ts";
import type { Output } from "./init.ts";
import { VERSION } from "./package-info.ts";

export const START = "<!-- peer-ai:start -->";
export const END = "<!-- peer-ai:end -->";
const GENERATED = `<!-- Generated by peer-ai render from ${CONFIG_FILE}. Change the config and run peer-ai render; edits inside this block are replaced. -->`;
const SERVER = "peer-ai";
const IMPORTS_AGENTS = /^@AGENTS\.md\s*$/m;

/** What render does to one file. `content` is the whole file to write, when it changes. */
export interface Planned {
  path: string;
  action: "create" | "update" | "unchanged" | "refused";
  content?: string;
  note?: string;
}

export interface RenderPlan {
  files: Planned[];
  /** Steps render can't take inside the project, such as a tool that keeps servers in the user's own config. */
  manual: string[];
}

/** How AI tools start the server: the project's own pinned copy, or this exact version. */
export function serverCommand(root: string): { command: string; args: string[] } {
  const pkg = readJson(join(root, "package.json")) as
    { dependencies?: Record<string, string>; devDependencies?: Record<string, string> } | undefined;
  const pinned = pkg?.devDependencies?.["peer-ai"] ?? pkg?.dependencies?.["peer-ai"];
  return pinned === undefined
    ? { command: "npx", args: ["-y", `peer-ai@${VERSION}`, "mcp"] }
    : { command: "npx", args: ["peer-ai", "mcp"] };
}

function readJson(path: string): unknown {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return undefined;
  }
}

function readText(root: string, path: string): string | undefined {
  const full = join(root, path);
  return existsSync(full) ? readFileSync(full, "utf8") : undefined;
}

/** The instructions every tool gets: short, because the MCP server serves the detail on demand. */
export function instructions(config: PeerAiConfig): string {
  const { project } = config;
  const lines = [
    "## Peer AI",
    "",
    `This project uses Peer AI${project.stage === undefined ? "" : ` at the ${project.stage} stage`}. Its MCP server, \`${SERVER}\`, holds the project map, the work items, and the gates work must pass before it ships.`,
    "",
    "- Start each session with `next_work`. It returns the work item for the current branch and where it stopped. For new work, create one with `create_work_item`.",
    "- Keep the item's stage current with `advance_work_item`: `build` before you change code, `verify` once the change is complete, `ship` when it is verified, reviewed and ready to merge, and `done` once it is merged or released. When it refuses, fix what it lists.",
    "- Before editing a file, call `standards_for_file` and follow what it returns.",
    "- Record progress with `update_work_item`, so the next session resumes where this one stopped.",
    "- Verify with `run_verify`. Never report a verify result yourself.",
    "- Record every review with `record_review`, including failed and incomplete ones.",
    "- Don't edit the files in `.peer-ai/` by hand. The tools keep them valid.",
  ];
  const ownTracks = config.tracks.filter((track) => track.status !== "external");
  if (config.tracks.length > 1) {
    lines.push("", "Parts of the project:", "");
    for (const track of config.tracks) {
      const where =
        track.status === "external"
          ? `in ${track.repo ?? "another repository"}`
          : (track.path ?? "the repository root");
      lines.push(`- \`${track.id}\` (${track.kind}, ${track.status}): ${where}`);
    }
  } else if (ownTracks[0] !== undefined) {
    lines.push("", `The project is one ${ownTracks[0].kind} part, \`${ownTracks[0].id}\`.`);
  }
  const commands = Object.entries(config.commands ?? {}).filter(
    (entry): entry is [string, string] => typeof entry[1] === "string",
  );
  if (commands.length > 0) {
    lines.push("", `Commands: ${commands.map(([name, command]) => `${name} \`${command}\``).join(", ")}.`);
  }
  const compliance = config.compliance;
  const packs = [...(compliance?.packs ?? [])];
  if (packs.length + (compliance?.jurisdictions?.length ?? 0) > 0) {
    const where = compliance?.jurisdictions === undefined ? "" : ` for ${compliance.jurisdictions.join(", ")}`;
    lines.push("", `Compliance${where}: ${packs.length === 0 ? "rule packs to be chosen" : packs.join(", ")}.`);
  }
  if ((config.rules ?? []).length > 0) {
    lines.push("", "Every change respects the project's own rules:", "");
    for (const rule of config.rules ?? []) {
      lines.push(`- \`${rule.path}\`${rule.description === undefined ? "" : `: ${rule.description}`}`);
    }
  }
  lines.push("", "If the peer-ai tools aren't available, run `npx peer-ai doctor`.");
  return lines.join("\n");
}

const block = (body: string) => `${START}\n${GENERATED}\n\n${body}\n${END}`;

/** The file with its marked block written or replaced, and nothing outside the block touched. */
function withBlock(path: string, existing: string | undefined, body: string): Planned {
  const wanted = block(body);
  if (existing === undefined) return { path, action: "create", content: `${wanted}\n` };
  const start = existing.indexOf(START);
  if (start === -1) {
    const separator = existing === "" ? "" : existing.endsWith("\n") ? "\n" : "\n\n";
    return { path, action: "update", content: `${existing}${separator}${wanted}\n` };
  }
  const end = existing.indexOf(END, start);
  if (end === -1) {
    return {
      path,
      action: "refused",
      note: `It has ${START} but no ${END} after it. Add the end marker, or remove the start marker, then render again.`,
    };
  }
  const content = `${existing.slice(0, start)}${wanted}${existing.slice(end + END.length)}`;
  return { path, action: content === existing ? "unchanged" : "update", content };
}

/** Registers the server under `key` in a JSON config, keeping every other entry as it is. */
function withServer(root: string, path: string, key: string, entry: Record<string, unknown>): Planned {
  const existing = readText(root, path);
  if (existing === undefined) {
    return { path, action: "create", content: `${JSON.stringify({ [key]: { [SERVER]: entry } }, null, 2)}\n` };
  }
  const parsed = readJson(join(root, path));
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    return {
      path,
      action: "refused",
      note: `It isn't plain JSON (comments aren't supported here), so add this under "${key}" by hand: "${SERVER}": ${JSON.stringify(entry)}`,
    };
  }
  const config = parsed as Record<string, unknown>;
  const servers = (typeof config[key] === "object" && config[key] !== null ? config[key] : {}) as Record<
    string,
    unknown
  >;
  if (JSON.stringify(servers[SERVER]) === JSON.stringify(entry)) return { path, action: "unchanged" };
  const content = `${JSON.stringify({ ...config, [key]: { ...servers, [SERVER]: entry } }, null, 2)}\n`;
  return { path, action: "update", content };
}

function cursorRule(body: string): string {
  return [
    "---",
    "description: How to work in this project with Peer AI",
    "alwaysApply: true",
    "---",
    "",
    GENERATED.replace("edits inside this block are replaced", "this file is replaced"),
    "",
    body,
    "",
  ].join("\n");
}

/**
 * A tool's own instructions file. When AGENTS.md carries the block, a new file just imports it, so
 * the tool doesn't read the instructions twice; an existing file that imports it is left alone.
 */
function toolFile(root: string, path: string, body: string, agentsRendered: boolean): Planned {
  const existing = readText(root, path);
  if (existing === undefined && agentsRendered) {
    return { path, action: "create", content: "@AGENTS.md\n", note: "It imports AGENTS.md." };
  }
  if (existing !== undefined && IMPORTS_AGENTS.test(existing) && !existing.includes(START)) {
    return { path, action: "unchanged", note: "It imports AGENTS.md, which carries the instructions." };
  }
  return withBlock(path, existing, body);
}

export function planRender(root: string, config: PeerAiConfig): RenderPlan {
  const tools: ToolId[] = config.tools ?? [];
  const body = instructions(config);
  const server = serverCommand(root);
  const files: Planned[] = [];
  const manual: string[] = [];
  const uses = (tool: ToolId) => tools.includes(tool);
  const imports = (path: string) => IMPORTS_AGENTS.test(readText(root, path) ?? "");

  // AGENTS.md is the file most tools read. A project that only uses Claude Code gets it when it
  // already has one, or when CLAUDE.md or GEMINI.md imports it.
  const agents =
    tools.length === 0 ||
    tools.some((tool) => tool !== "claude-code") ||
    existsSync(join(root, "AGENTS.md")) ||
    imports("CLAUDE.md");
  if (agents) files.push(withBlock("AGENTS.md", readText(root, "AGENTS.md"), body));

  if (uses("claude-code")) {
    files.push(toolFile(root, "CLAUDE.md", body, agents));
    files.push(withServer(root, ".mcp.json", "mcpServers", server));
  }
  if (uses("cursor")) {
    const path = ".cursor/rules/peer-ai.mdc";
    const content = cursorRule(body);
    const existing = readText(root, path);
    files.push({
      path,
      action: existing === undefined ? "create" : existing === content ? "unchanged" : "update",
      content,
    });
    files.push(withServer(root, ".cursor/mcp.json", "mcpServers", server));
  }
  if (uses("copilot")) {
    files.push(withBlock(".github/copilot-instructions.md", readText(root, ".github/copilot-instructions.md"), body));
    files.push(withServer(root, ".vscode/mcp.json", "servers", { type: "stdio", ...server }));
  }
  if (uses("gemini-cli")) {
    files.push(toolFile(root, "GEMINI.md", body, agents));
    files.push(withServer(root, ".gemini/settings.json", "mcpServers", server));
  }
  if (uses("codex")) {
    manual.push(
      `Codex keeps MCP servers in your own config, not the project's. Register it once: codex mcp add ${SERVER} -- ${server.command} ${server.args.join(" ")}`,
    );
  }
  if (uses("other")) {
    manual.push(
      `For another tool, point it at AGENTS.md, and register the MCP server as: ${server.command} ${server.args.join(" ")}`,
    );
  }
  return { files, manual };
}

function write(root: string, planned: Planned): void {
  if (planned.content === undefined) return;
  const full = join(root, planned.path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, planned.content);
}

function toCheck(planned: Planned, checking: boolean): Check {
  switch (planned.action) {
    case "refused":
      return fail("render", `${planned.path} wasn't changed.`, planned.note ?? "");
    case "unchanged":
      return ok("render", `${planned.path} is up to date.${planned.note === undefined ? "" : ` ${planned.note}`}`);
    default:
      return checking
        ? fail("render", `${planned.path} is out of date.`, "Run peer-ai render.")
        : ok(
            "render",
            `${planned.path} ${planned.action === "create" ? "created" : "updated"}.${planned.note === undefined ? "" : ` ${planned.note}`}`,
          );
  }
}

export interface RenderOptions {
  cwd: string;
  /** Change nothing; fail when a file is out of date. For CI. */
  check: boolean;
}

/** Exit code 0 when done or up to date; 1 when a file was refused, or out of date with --check; 2 without a valid config. */
export function runRender(options: RenderOptions, out: Output): number {
  const { config, errors } = loadConfig(options.cwd);
  if (config === undefined) {
    if (errors === undefined) out.error(`There is no ${CONFIG_FILE}. Run peer-ai init first.`);
    else {
      out.error(`${CONFIG_FILE} is not valid:`);
      for (const error of errors) out.error(`  ${error}`);
    }
    return 2;
  }
  const plan = planRender(options.cwd, config);
  if (!options.check) for (const planned of plan.files) if (planned.action !== "refused") write(options.cwd, planned);
  const checks = plan.files.map((planned) => toCheck(planned, options.check));
  if ((config.tools ?? []).length === 0) {
    checks.push(skip("render", `No AI tools are listed in ${CONFIG_FILE}, so only AGENTS.md was written.`));
  }
  out.log(`Peer AI render: ${config.project.name}`);
  out.log("");
  for (const line of formatChecks(checks)) out.log(line);
  for (const step of plan.manual) out.log(`  ! ${step}`);
  const failures = count(checks, "fail");
  out.log("");
  if (options.check) out.log(failures === 0 ? "Everything is up to date." : "Out of date: run peer-ai render.");
  else if (failures > 0) out.log("Some files couldn't be changed; see above.");
  else out.log("Done. Commit these files, so every clone and every tool gets them.");
  return failures === 0 ? 0 : 1;
}
