// Ruff's settings for a project's Python profiles (RFC 0006). Ruff reads settings from a file, not
// a package, so render writes them to .peer-ai/enforce/ruff.toml and the project's own Ruff
// settings extend it. Every automatic rule Ruff enforces is selected, with the project's values.

import { profileRulesFor, type AppliedRule } from "peer-ai-standards";
import { reportsOnly, type PeerAiConfig } from "peer-ai-workflow";
import { ENFORCING, type Enforcement } from "./stages.ts";
import { stringify } from "smol-toml";

export const RUFF_FILE = ".peer-ai/enforce/ruff.toml";

type Table = Record<string, unknown>;

/**
 * Ruff's lint settings for these rules, with the settings they read merged in. The rules are added
 * with extend-select, which keeps Ruff's defaults and the project's own choices: a select would
 * replace them.
 */
export function ruffSettings(rules: readonly AppliedRule[]): { lint: Table } {
  const codes = new Set<string>();
  const lint: Record<string, Table> = {};
  for (const rule of rules) {
    if (rule.check !== "auto" || rule.enforcer?.tool !== "ruff") continue;
    codes.add(rule.enforcer.rule);
    for (const [section, settings] of Object.entries(rule.enforcer.settings ?? {})) {
      lint[section] = { ...lint[section], ...settings };
    }
  }
  return { lint: { "extend-select": [...codes].sort(), ...lint } };
}

/** The automatic Ruff rules any part of the project gets, leaving out the ones it set aside. */
export function ruffRules(config: PeerAiConfig): AppliedRule[] {
  const setAside = new Set((config.standards?.exceptions ?? []).map((exception) => exception.rule));
  const seen = new Map<string, AppliedRule>();
  for (const track of config.tracks) {
    if (track.status === "external") continue;
    const rules = profileRulesFor({
      listed: config.standards?.profiles ?? [],
      stage: config.project.stage ?? "mvp",
      traits: config.project.traits ?? [],
      overrides: config.standards?.overrides ?? {},
      ...(track.stack === undefined ? {} : { stack: track.stack }),
      ...(track.architecture === undefined ? {} : { architecture: track.architecture }),
    });
    for (const rule of rules) {
      if (rule.enforcer?.tool === "ruff" && rule.check === "auto" && !setAside.has(rule.id)) seen.set(rule.id, rule);
    }
  }
  return [...seen.values()];
}

/** Settings as TOML. */
export const toToml = (settings: Table): string => stringify(settings);

/** The file render writes, or undefined when no part gets a Ruff rule. */
export function ruffFile(config: PeerAiConfig, enforcement: Enforcement = ENFORCING): string | undefined {
  const all = ruffRules(config);
  if (all.length === 0) return undefined;
  // Ruff has no warnings, so a rule that only reports for now is left out until it enforces (RFC 0011).
  const rules = all.filter((rule) => !reportsOnly(enforcement.adoption, rule.id));
  const reported = all.filter((rule) => reportsOnly(enforcement.adoption, rule.id));
  const code = (rule: AppliedRule) => `${rule.id} ${rule.enforcer?.tool === "ruff" ? rule.enforcer.rule : ""}`;
  return `${[
    "# Generated by peer-ai render from peer-ai.config.json: the Ruff rules of the project's stack profiles.",
    '# Ruff reads it only when your own Ruff settings extend it, such as extend = ".peer-ai/enforce/ruff.toml"',
    "# under [tool.ruff], and then it only adds rules: your own settings stay as they are. Add rules of your",
    "# own with extend-select, not select, which would replace these. Change the config, not this file:",
    "# render writes it again.",
    `# ${rules.length === 0 ? "No rules enforce yet." : rules.map(code).join(", ")}`,
    ...(reported.length === 0
      ? []
      : [`# Reporting only for now, so left out until they enforce: ${reported.map(code).join(", ")}`]),
    "",
    toToml(ruffSettings(rules)),
  ].join("\n")}\n`;
}
