// Ruff's settings for a project's Python profiles (RFC 0006). Ruff reads settings from a file, not
// a package, so render writes them to .peer-ai/enforce/ruff.toml and the project's own Ruff
// settings extend it. Every automatic rule Ruff enforces is selected, with the project's values.

import { profileRulesFor, type AppliedRule } from "@peer-ai/standards";
import type { PeerAiConfig } from "@peer-ai/workflow";

export const RUFF_FILE = ".peer-ai/enforce/ruff.toml";

type Table = Record<string, unknown>;

/** Ruff's lint settings for these rules: each selected, and the settings they read merged in. */
export function ruffSettings(rules: readonly AppliedRule[]): { lint: Table } {
  const select = new Set<string>();
  const lint: Table = {};
  for (const rule of rules) {
    if (rule.check !== "auto" || rule.enforcer?.tool !== "ruff") continue;
    select.add(rule.enforcer.rule);
    for (const [section, settings] of Object.entries(rule.enforcer.settings ?? {})) {
      lint[section] = { ...(lint[section] as Table | undefined), ...(settings as Table) };
    }
  }
  return { lint: { select: [...select].sort(), ...lint } };
}

/** The automatic Ruff rules any part of the project gets, leaving out the ones it set aside. */
export function ruffRules(config: PeerAiConfig): AppliedRule[] {
  const setAside = new Set((config.standards?.exceptions ?? []).map((exception) => exception.rule));
  const seen = new Map<string, AppliedRule>();
  for (const track of config.tracks) {
    if (track.status === "external") continue;
    const rules = profileRulesFor({
      listed: config.standards?.profiles ?? [],
      stage: config.project.stage ?? "mvp",
      traits: config.project.traits ?? [],
      overrides: config.standards?.overrides ?? {},
      ...(track.stack === undefined ? {} : { stack: track.stack }),
      ...(track.architecture === undefined ? {} : { architecture: track.architecture }),
    });
    for (const rule of rules) {
      if (rule.enforcer?.tool === "ruff" && rule.check === "auto" && !setAside.has(rule.id)) seen.set(rule.id, rule);
    }
  }
  return [...seen.values()];
}

const tomlValue = (value: unknown): string =>
  Array.isArray(value) ? `[${value.map(tomlValue).join(", ")}]` : JSON.stringify(value);

/** Settings as TOML: plain values first, then each table under its dotted name. */
export function toToml(settings: Table, prefix = ""): string {
  const plain = Object.entries(settings).filter(([, value]) => typeof value !== "object" || Array.isArray(value));
  const tables = Object.entries(settings).filter(([, value]) => typeof value === "object" && !Array.isArray(value));
  const lines = plain.map(([key, value]) => `${key} = ${tomlValue(value)}`);
  const head = prefix === "" || plain.length === 0 ? [] : [`[${prefix}]`];
  const body = [...head, ...lines].join("\n");
  const rest = tables.map(([key, value]) => toToml(value as Table, prefix === "" ? key : `${prefix}.${key}`));
  return [body, ...rest].filter((part) => part !== "").join("\n\n");
}

/** The file render writes, or undefined when no part gets a Ruff rule. */
export function ruffFile(config: PeerAiConfig): string | undefined {
  const rules = ruffRules(config);
  if (rules.length === 0) return undefined;
  const ids = rules.map((rule) => `${rule.id} ${rule.enforcer?.tool === "ruff" ? rule.enforcer.rule : ""}`);
  return `${[
    "# Generated by peer-ai render from peer-ai.config.json: the Ruff rules of the project's stack profiles.",
    '# Extend it from your own Ruff settings, such as extend = ".peer-ai/enforce/ruff.toml", and change',
    "# the config, not this file: render writes it again.",
    `# ${ids.join(", ")}`,
    "",
    toToml(ruffSettings(rules)),
  ].join("\n")}\n`;
}
