// The update pull request (RFC 0014): with updates.pullRequest, render writes a daily workflow that
// opens "Update Peer AI to <version>" when npm has a newer release than the project pins, with
// render already run on a branch. It owns the file the way it owns its other workflows.

import { FEEDBACK_REPO } from "./feedback.ts";
import { CHECKOUT, SETUP_NODE, withHash } from "./pipeline.ts";

export const UPDATE_FILE = ".github/workflows/peer-ai-update.yml";

/** The workflow, pinned to the version render runs as, which is the version the project uses. */
export function updateWorkflow(version: string): string {
  const script = [
    "set -euo pipefail",
    'latest="$(npm view peer-ai dist-tags.latest)"',
    // Only a version goes into a branch name, a command or a title.
    'if ! [[ "$latest" =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-[0-9A-Za-z.]+)?$ ]]; then echo "npm gave no version"; exit 1; fi',
    `if [ "$latest" = "${version}" ]; then echo "Peer AI ${version} is the latest release."; exit 0; fi`,
    'branch="peer-ai/update-$latest"',
    'if [ "$(gh pr list --head "$branch" --state open --json number --jq length)" != "0" ]; then echo "A pull request for $latest is open already."; exit 0; fi',
    'git switch -c "$branch"',
    'npx -y "peer-ai@$latest" render',
    "git add -A",
    'if git diff --cached --quiet; then echo "Nothing to change for $latest."; exit 0; fi',
    'git -c user.name="peer-ai update" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -q -m "chore: update Peer AI to $latest"',
    'auth="$(printf "x-access-token:%s" "$GH_TOKEN" | base64 -w0)"',
    'git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic $auth" push -q origin "$branch"',
    `body="Peer AI $latest is out, and this project uses ${version}. This pull request ran npx peer-ai@$latest render. What changed: https://github.com/${FEEDBACK_REPO}/releases"`,
    'body="$body"$\'\\n\\n\'"Review it and merge it, then reconnect each AI tool to Peer AI, or restart it, right away: until then, a tool still running the older version may refuse the newer config."',
    'if [ "$OWN_TOKEN" = "true" ]; then body="$body"$\'\\n\\n\'"CI doesn\'t start on a pull request opened with the workflow\'s own token: close and reopen this one to run the checks, or add a PEER_AI_UPDATE_TOKEN secret so the next one runs them by itself."; fi',
    'gh pr create --head "$branch" --title "Update Peer AI to $latest" --body "$body"',
  ];
  const body = [
    "name: Peer AI update",
    "on:",
    "  schedule:",
    '    - cron: "41 5 * * *"',
    "  workflow_dispatch:",
    "permissions: {}",
    "jobs:",
    "  update:",
    "    name: peer-ai update",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 15",
    "    permissions:",
    "      contents: write",
    "      pull-requests: write",
    "    steps:",
    `      - uses: ${CHECKOUT}`,
    "        with:",
    "          persist-credentials: false",
    `      - uses: ${SETUP_NODE}`,
    "        with:",
    "          node-version: 24",
    "      - name: Open a pull request when a newer Peer AI is out",
    "        env:",
    // A token of the project's own lets CI run on the pull request; the workflow's own doesn't.
    "          GH_TOKEN: ${{ secrets.PEER_AI_UPDATE_TOKEN || github.token }}",
    "          OWN_TOKEN: ${{ secrets.PEER_AI_UPDATE_TOKEN == '' }}",
    "        run: |",
    ...script.map((line) => `          ${line}`),
    "",
  ].join("\n");
  return withHash(
    [
      "# Generated by peer-ai render from peer-ai.config.json: the update pull request (RFC 0014).",
      "# Change the config, not this file. Render writes it again while it's as render left it, and leaves",
      "# it alone once someone changes it by hand. Set updates.pullRequest to false to stop it.",
    ],
    body,
  );
}

/** Whether a project pins peer-ai in package.json, which Dependabot or Renovate update, with its lockfile. */
export function pinnedInPackageJson(manifest: string | undefined): boolean {
  if (manifest === undefined) return false;
  try {
    const parsed = JSON.parse(manifest) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    return parsed.devDependencies?.["peer-ai"] !== undefined || parsed.dependencies?.["peer-ai"] !== undefined;
  } catch {
    return false;
  }
}
