import type { ProfileInput } from "../profile.ts";

// Express. It builds on Node. Its layering rules apply only where a part declares that
// architecture, so a modular monolith and a layered API each get their own. Examples are from a
// made-up bicycle repair booking service.

export const express: ProfileInput = {
  id: "express",
  name: "Express",
  prefix: "EXPRESS",
  about:
    "APIs in Express: bodies with a limit, input checked at the route, one error handler that keeps internals in, security headers, and callers from a fixed list. Its layering rules follow the architecture a part declares. It builds on the Node profile.",
  stacks: ["express"],
  extends: ["node"],
  rules: [
    {
      id: "EXPRESS-01",
      title: "Request bodies stay under {value}",
      rule: 'Body parsers keep a size limit, such as `express.json({ limit: "{value}" })`, raised only for a route that needs more, such as an upload.',
      why: "A body with no limit lets one request fill the server's memory.",
      ask: "Does every body parser in this change keep a size limit?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "BE-02",
      default: { value: "100kb" },
    },
    {
      id: "EXPRESS-02",
      title: "Input is checked at the route",
      rule: "Every route checks its body, parameters and query against a schema before anything else uses them.",
      why: "Express passes on whatever arrives. Unchecked input is how wrong types, extra fields and injections reach the business rules.",
      ask: "Does every route in this change check its input against a schema?",
      stage: "prototype",
      check: "ai-review",
      severity: "high",
      carries: "SEC-05",
    },
    {
      id: "EXPRESS-03",
      title: "One error handler, and no internals in its answer",
      rule: "Errors reach one error handler, which answers in the project's error shape, without stack traces, queries or file paths.",
      why: "Express's default answer to an error shows the stack trace outside production, and a missed setting shows it in production.",
      ask: "Could an error in this change send internal detail to the client?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "SEC-09",
    },
    {
      id: "EXPRESS-04",
      title: "Every response sets its security headers",
      rule: "The security headers are set for every response, such as with `helmet`, before any route.",
      why: "Express sets none by default, so a browser gives its pages none of the protections the headers switch on.",
      ask: "Are the security headers set before every route?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "SEC-17",
    },
    {
      id: "EXPRESS-05",
      title: "Cross-origin callers come from a fixed list",
      rule: "CORS allows only a fixed list of the project's own origins, never `*` for a route that uses cookies or tokens.",
      why: "An open CORS policy lets any site call the API with the visitor's credentials.",
      ask: "Does the CORS policy allow only a fixed list of origins?",
      stage: "mvp",
      check: "ai-review",
      severity: "high",
      carries: "SEC-16",
    },
    {
      id: "EXPRESS-06",
      title: "Routes call services, never the database",
      rule: "In a layered API, a route reads the request, calls a service and answers. Only the data layer queries the database.",
      why: "A route that queries the database skips the rules the service enforces, and the next change has to find every copy.",
      ask: "Does any route in this change reach the database without its service?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "ARC-07",
      architectures: ["layered"],
    },
    {
      id: "EXPRESS-07",
      title: "Modules use each other only through what they export",
      rule: "In a modular monolith, each module's routes, services and data stay inside it. Another module imports only what the module's index exports.",
      why: "Reaching into another module's files ties the two together, so neither can change alone.",
      ask: "Does this change import another module's internal files?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "ARC-03",
      architectures: ["modular-monolith"],
    },
  ],
};
