import type { ProfileInput } from "../profile.ts";

// FastAPI. It builds on Python. Its layering rules apply only where a part declares that
// architecture, so a modular monolith and a layered API each get their own. Examples are from a
// made-up bicycle repair booking service.

export const fastapi: ProfileInput = {
  id: "python-fastapi",
  name: "FastAPI",
  prefix: "FASTAPI",
  about:
    "APIs in FastAPI: models for what comes in and what goes out, permission checked per record, settings checked at start-up, callers from a fixed list, errors that keep internals in, and a body limit set somewhere. Its layering rules follow the architecture a part declares. It builds on the Python profile.",
  stacks: ["fastapi"],
  extends: ["python"],
  rules: [
    {
      id: "FASTAPI-01",
      title: "Every route has models for what comes in and goes out",
      rule: "Every route takes its body as a Pydantic model and declares its response model, so FastAPI checks what arrives and sends only the fields the response names.",
      why: "A route that returns a database object sends every field it has, including ones the client should never see.",
      ask: "Does every route in this change declare request and response models?",
      stage: "prototype",
      check: "ai-review",
      severity: "high",
      carries: "SEC-05",
    },
    {
      id: "FASTAPI-02",
      title: "Permission is checked for the record, not only the person",
      rule: "A route that takes an id checks the caller may use that record, such as in a dependency that loads it for the caller, not only that they're signed in.",
      why: "A dependency that only checks sign-in lets anyone signed in change an id in the URL and read someone else's record.",
      ask: "Does every route in this change that takes an id check the caller may use that record?",
      stage: "mvp",
      check: "ai-review",
      severity: "critical",
      carries: "SEC-01",
    },
    {
      id: "FASTAPI-03",
      title: "Settings are checked when the app starts",
      rule: "Settings are a Pydantic settings class, loaded once at start-up, so the app refuses to start with a setting missing or wrong, and an environment name it doesn't know is treated as production.",
      why: "A setting read with os.environ where it's used fails the first request that needs it, long after the deploy looked fine.",
      ask: "Does this change read a setting outside the settings class?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "REL-04",
    },
    {
      id: "FASTAPI-04",
      title: "Cross-origin callers come from a fixed list",
      rule: "`CORSMiddleware` allows only a fixed list of the project's own origins, never `*` with credentials.",
      why: "An open CORS policy lets any site call the API with the visitor's credentials.",
      ask: "Does the CORS middleware allow only a fixed list of origins?",
      stage: "mvp",
      check: "ai-review",
      severity: "high",
      carries: "SEC-16",
    },
    {
      id: "FASTAPI-05",
      title: "Errors keep internals in",
      rule: "Exception handlers answer in the project's error shape, without tracebacks, queries or driver errors, and `debug` is off outside development.",
      why: "With debug on, or a handler that passes on an exception's text, such as `HTTPException(detail=str(error))`, a database error reaches the client with the query and the table names in it.",
      ask: "Could an error in this change reach the client with internal detail?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "SEC-09",
    },
    {
      id: "FASTAPI-06",
      title: "Request bodies stay under {value}",
      rule: "Something limits request bodies to {value}, such as the proxy in front or a middleware like Starlette's `RequestBodyLimitMiddleware`, since FastAPI sets no limit itself.",
      why: "With no limit, one request can fill the server's memory.",
      ask: "What limits the size of a request body, and is it {value} or less?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "BE-02",
      default: { value: "1 MiB" },
    },
    {
      id: "FASTAPI-07",
      title: "Routes call services, never the session",
      rule: "In a layered API, a route reads the request, calls a service and answers. Only the data layer uses the database session.",
      why: "A route that queries the session skips the rules the service enforces, and the next change has to find every copy.",
      ask: "Does any route in this change use the database session directly?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "ARC-07",
      architectures: ["layered"],
    },
    {
      id: "FASTAPI-08",
      title: "Each domain keeps its router, services and models to itself",
      rule: "In a modular monolith, each domain's package holds its router, services and models. Another domain imports only what the package's public module exports.",
      why: "Reaching into another domain's models or services ties the two together, so neither can change alone.",
      ask: "Does this change import another domain's internal modules?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "ARC-03",
      architectures: ["modular-monolith"],
    },
  ],
};
