import type { ProfileInput } from "../profile.ts";

// NestJS. It builds on Node. Examples are from a made-up bicycle repair booking service.

export const nestjs: ProfileInput = {
  id: "nestjs",
  name: "NestJS",
  prefix: "NEST",
  about:
    "APIs in NestJS: a validation pipe that refuses unknown fields, guards on every controller, thin controllers, an exception filter that keeps internals in, and settings checked at start-up. It builds on the Node profile.",
  stacks: ["nest"],
  extends: ["node"],
  rules: [
    {
      id: "NEST-01",
      title: "A global validation pipe refuses unknown fields",
      rule: "A global `ValidationPipe` runs with `whitelist` and `forbidNonWhitelisted`, and every request body is a DTO class with validation decorators.",
      why: "Without the pipe, a DTO's decorators do nothing, and a body with extra fields, such as a role, reaches the service as it came.",
      ask: "Does the app run a global ValidationPipe that refuses unknown fields, and does every body have a validated DTO?",
      stage: "prototype",
      check: "ai-review",
      severity: "high",
      carries: "SEC-05",
    },
    {
      id: "NEST-02",
      title: "Every route is guarded unless it says it's public",
      rule: "An authentication guard is global, and a route open to everyone says so with a decorator, such as `@Public()`, which a reviewer can see.",
      why: "A guard added controller by controller is missed on the one controller that needed it.",
      ask: "Is every route in this change behind the guard, or marked public on purpose?",
      stage: "mvp",
      check: "ai-review",
      severity: "critical",
      carries: "SEC-03",
    },
    {
      id: "NEST-03",
      title: "Controllers call services, which hold the rules",
      rule: "A controller maps the request to a service call and the result to a response. The business rules live in the service, which knows nothing of HTTP.",
      why: "Rules in a controller can't be reused by a queue consumer or a scheduled job, and are tested only through HTTP.",
      ask: "Does any controller in this change hold a business rule?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "ARC-05",
    },
    {
      id: "NEST-04",
      title: "An exception filter keeps internals in",
      rule: "A global exception filter answers every error in the project's error shape, without stack traces, queries or database errors.",
      why: "An error the filter doesn't know about, such as a database error, otherwise reaches the client with its detail.",
      ask: "Could an error in this change reach the client with internal detail?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "SEC-09",
    },
    {
      id: "NEST-05",
      title: "Settings are checked when the app starts",
      rule: "`ConfigModule` loads settings with a validation schema, so the app refuses to start with a setting missing or wrong.",
      why: "A setting read unchecked fails on the first request that needs it, long after the deploy looked fine.",
      ask: "Does the app check its settings with a schema at start-up?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "REL-04",
    },
    {
      id: "NEST-06",
      title: "Modules share only the providers they export",
      rule: "A module uses another only through the providers that module exports, never by importing its internal files.",
      why: "Reaching past a module's exports ties the two together, so neither can change alone.",
      ask: "Does this change reach into another module past its exports?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "ARC-03",
    },
  ],
};
