import type { ProfileInput } from "../profile.ts";

// React Native, with or without Expo. It builds on React, whose web-only rules don't match native
// components. Examples are from a made-up bicycle repair booking service.

export const reactNative: ProfileInput = {
  id: "react-native",
  name: "React Native",
  prefix: "RN",
  about:
    "Phone apps in React Native, with or without Expo: text that follows the person's size, nothing written to the device log, secrets in the platform's secure store, and the checks a phone app needs before it's trusted with people's data. It builds on the React profile.",
  stacks: ["react-native", "expo"],
  extends: ["react"],
  rules: [
    {
      id: "RN-01",
      title: "Text follows the person's text size",
      rule: "Text isn't stopped from scaling with `allowFontScaling={false}`. A layout that breaks at large sizes is fixed, such as by wrapping or scrolling, not by ignoring the setting.",
      why: "People who set a larger text size need it to read at all; an app that ignores it is unusable to them.",
      ask: "Does this change stop any text from following the person's text size?",
      stage: "mvp",
      check: "auto",
      severity: "medium",
      carries: "DES-14",
      enforcer: {
        tool: "eslint",
        rule: "no-restricted-syntax",
        options: [
          {
            selector: "JSXAttribute[name.name='allowFontScaling'][value.expression.value=false]",
            message: "RN-01: text follows the person's text size. Fix the layout instead of turning scaling off.",
          },
        ],
      },
      examples: {
        file: "example.tsx",
        fails:
          'import { Text } from "react-native";\nexport function Price() {\n  return <Text allowFontScaling={false}>£45 service</Text>;\n}\n',
        passes:
          'import { Text } from "react-native";\nexport function Price() {\n  return <Text>£45 service</Text>;\n}\n',
      },
    },
    {
      id: "RN-02",
      title: "Nothing is written to the device log",
      rule: "The app doesn't call `console`. What needs recording goes through the project's logger, which drops personal data and sends nothing from release builds.",
      why: "On a phone, the console goes to the device log, which crash tools collect and anyone with the phone on a cable can read.",
      ask: "Does this change call console?",
      stage: "mvp",
      check: "auto",
      severity: "medium",
      carries: "MOB-02",
      enforcer: { tool: "eslint", rule: "no-console" },
      examples: {
        file: "example.ts",
        fails: "export function signIn(email: string): void {\n  console.log(`signing in ${email}`);\n}\n",
        passes:
          'export function signIn(email: string, log: (event: string) => void): void {\n  log(email.length > 0 ? "sign-in started" : "sign-in without an email");\n}\n',
      },
    },
    {
      id: "RN-03",
      title: "Tokens and personal data are kept in secure storage",
      rule: "Session tokens, keys and personal data are kept in the platform's secure store, such as `expo-secure-store` or the Keychain and Keystore, never in AsyncStorage or a plain file.",
      why: "AsyncStorage is a plain file on the device, readable from a backup or a rooted phone.",
      ask: "Does this change keep a token or personal data outside secure storage?",
      stage: "mvp",
      check: "ai-review",
      severity: "high",
      carries: "MOB-01",
    },
    {
      id: "RN-04",
      title: "A web view opens only your own pages",
      rule: "A `WebView` loads only the project's own pages: `originWhitelist` lists them, links elsewhere open in the system browser, and JavaScript is on only where the page needs it.",
      why: "A web view that follows any link runs someone else's page inside the app, with whatever the app gave the web view.",
      ask: "Can any web view in this change load a page the project doesn't own?",
      stage: "mvp",
      check: "ai-review",
      severity: "high",
      carries: "MOB-03",
    },
    {
      id: "RN-05",
      title: "A link into the app is checked before it's used",
      rule: "Every value a deep link carries, such as an id or a URL, is checked before the app acts on it, like any other input from outside.",
      why: "Anyone can send a link that opens the app. A link that's trusted can open a page it shouldn't, or act as the person.",
      ask: "Does this change act on a deep link's values without checking them?",
      stage: "mvp",
      check: "ai-review",
      severity: "high",
      carries: "MOB-04",
    },
    {
      id: "RN-06",
      title: "Long lists use a list component",
      rule: "A list that can grow long is a `FlatList`, `SectionList` or another virtualised list, not a `ScrollView` of mapped items.",
      why: "A ScrollView draws every item at once, so the screen gets slower and uses more memory with every item.",
      ask: "Does this change draw a list that can grow long inside a ScrollView?",
      stage: "mvp",
      check: "ai-review",
      severity: "low",
      carries: "PERF-05",
    },
    {
      id: "RN-07",
      title: "Touch targets are at least {value} points",
      rule: "Everything a person taps is at least {value} by {value} points, using `hitSlop` where the visible part is smaller.",
      why: "A small target is missed by people with less precise hands, and by everyone on a moving bus.",
      ask: "Is anything tappable in this change smaller than {value} points?",
      stage: "mvp",
      check: "ai-review",
      severity: "low",
      carries: "DES-15",
      default: { value: 44, unit: "points" },
    },
    {
      id: "RN-08",
      title: "Permissions are asked for when they're needed",
      rule: "The app asks for a permission, such as location or the camera, when the person starts the feature that needs it, and at the least level that works, such as while in use.",
      why: "A permission asked for at launch is refused without being understood, and a wider one than needed is a risk the person didn't agree to.",
      ask: "Does this change ask for a permission before it's needed, or at a wider level than it needs?",
      stage: "mvp",
      check: "ai-review",
      severity: "medium",
      carries: "MOB-05",
    },
    {
      id: "RN-09",
      title: "The app can require an update",
      rule: "At start-up, the app asks the server for the lowest version it may run, and asks the person to update when it's below it, such as with Expo Updates or a store check.",
      why: "An installed app can't be recalled. Without a way to require an update, a version with a security hole stays in use.",
      ask: "Can the server require people to update this app?",
      stage: "production",
      check: "ai-review",
      severity: "high",
      carries: "MOB-06",
    },
  ],
};
