import type { RuleInput } from "../rule.ts";

// For products with the ai-features trait: features that use AI models. Rules cite the entry of
// the OWASP Top 10 for Large Language Model Applications (2025) they come from, checked against
// OWASP's own repository.

const LLM = "OWASP Top 10 for LLM Applications 2025";
const entry = (file: string) =>
  `https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/blob/main/2_0_vulns/${file}.md`;

export const aiFeatures = [
  {
    id: "AI-01",
    domain: "ai-features",
    title: "An AI's output is untrusted input",
    rule: "Output from an AI model is checked and escaped like any outside input before it's shown, stored, or passed to code, a database, a shell or another service.",
    why: "What a model says can be steered by what it was given, so its output can carry an attack as easily as a user's input can.",
    ask: "Is every AI output in this change checked and escaped before it's used?",
    stage: "prototype",
    check: "ai-review",
    severity: "high",
    when: ["ai-features"],
    sources: [{ name: LLM, ref: "LLM05, Improper Output Handling", url: entry("LLM05_ImproperOutputHandling") }],
  },
  {
    id: "AI-02",
    domain: "ai-features",
    title: "An AI's guess is never shown as fact",
    rule: "An AI's answer is shown as a suggestion, never as fact. Anything about safety, health, money or the law also tells the person to check with someone qualified.",
    why: "Models state wrong answers as confidently as right ones, and a wrong answer about whether a plant is safe for a pet can hurt someone.",
    ask: "Does this change show any AI answer as fact, or give safety advice without telling the person to check?",
    stage: "prototype",
    check: "ai-review",
    severity: "high",
    when: ["ai-features"],
    sources: [{ name: LLM, ref: "LLM09, Misinformation", url: entry("LLM09_Misinformation") }],
  },
  {
    id: "AI-03",
    domain: "ai-features",
    title: "People know what's sent to an AI service, and nothing sensitive goes without need",
    rule: "People are told what's sent to an AI service before it's sent. Personal or sensitive data is sent only when the feature needs it, and removed when it doesn't.",
    why: "Data sent to a model provider can be logged, kept or used for training, and people didn't agree to that just by using a feature.",
    ask: "Does this change send an AI service anything people haven't been told about, or don't need to send?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
    when: ["ai-features"],
    sources: [
      { name: LLM, ref: "LLM02, Sensitive Information Disclosure", url: entry("LLM02_SensitiveInformationDisclosure") },
    ],
  },
  {
    id: "AI-04",
    domain: "ai-features",
    title: "Content can't change what the model is allowed to do",
    rule: "Instructions to the model and the content it works on are kept apart, and the model's permissions are enforced outside it, so text in a document, email or web page can't change what it's allowed to do.",
    why: "A line hidden in a web page can tell a model to ignore its instructions, and the model can't reliably tell instructions from content.",
    ask: "Could content the model reads in this change make it do something it shouldn't?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
    when: ["ai-features"],
    sources: [{ name: LLM, ref: "LLM01, Prompt Injection", url: entry("LLM01_PromptInjection") }],
  },
  {
    id: "AI-05",
    domain: "ai-features",
    title: "An AI does only what it needs to, and a person confirms what matters",
    rule: "An AI can call only the tools and data its task needs, with the least permission they allow, and anything that moves money, changes data or acts on someone's account needs a person's confirmation.",
    why: "A model given broad powers will eventually use them wrongly, whether by mistake or because someone tricked it.",
    ask: "Does the AI in this change have more access than its task needs, or act on anything important without confirmation?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
    when: ["ai-features"],
    sources: [{ name: LLM, ref: "LLM06, Excessive Agency", url: entry("LLM06_ExcessiveAgency") }],
  },
  {
    id: "AI-06",
    domain: "ai-features",
    title: "Instructions to the model hold no secrets",
    rule: "The instructions given to a model hold no secrets, credentials or rules that only work if nobody sees them.",
    why: "People can get a model to repeat its instructions, so anything in them should be safe to read.",
    ask: "Do the model's instructions in this change hold anything that would matter if someone read them?",
    stage: "prototype",
    check: "ai-review",
    severity: "medium",
    when: ["ai-features"],
    sources: [{ name: LLM, ref: "LLM07, System Prompt Leakage", url: entry("LLM07_SystemPromptLeakage") }],
  },
  {
    id: "AI-07",
    domain: "ai-features",
    title: "AI calls have limits",
    rule: "Every call to an AI service has a timeout and a size limit, and each person has a spending or usage limit.",
    why: "AI calls are slow and paid per use, so one runaway loop or one abusive user can take the feature down or run up a large bill.",
    ask: "Does every AI call in this change have a timeout, a size limit and a per-person limit?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
    when: ["ai-features"],
    sources: [{ name: LLM, ref: "LLM10, Unbounded Consumption", url: entry("LLM10_UnboundedConsumption") }],
  },
  {
    id: "AI-08",
    domain: "ai-features",
    title: "An AI feature is tested on fixed examples, attacks included",
    rule: "An AI feature has a set of example inputs with the behaviour expected for each, including attacks such as prompt injection and attempts to make it leak data or go beyond its permissions. They're run before every change to its instructions or its model.",
    why: "A small change to a prompt or a model version can quietly break answers that used to be right, and a model that resisted an attack last month may not after an update.",
    ask: "Were the AI feature's examples, attacks included, run for this change to its instructions or model?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
    when: ["ai-features"],
    sources: [{ name: LLM, ref: "LLM01, Prompt Injection", url: entry("LLM01_PromptInjection") }],
  },
] satisfies RuleInput[];
