import type { RuleInput } from "../rule.ts";

// How services and clients agree on what they send each other.

export const apiDesign = [
  {
    id: "API-01",
    domain: "api-design",
    title: "Requests and responses are typed schemas",
    rule: "Every request and response body is a typed schema, not a loose map or dictionary. The schema is the contract.",
    why: "A loose response becomes a loose client type, in every app that uses the API, at once.",
    ask: "Is every request and response body in this change a typed schema?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "API-02",
    domain: "api-design",
    title: "The contract has one source of truth",
    rule: "The API's contract has one source of truth, whether it's generated from the code's schemas or written by hand, and every client works from it.",
    why: "Two descriptions of one API disagree, and the client finds out in production.",
    ask: "Does this change keep the API contract's one source of truth up to date?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "API-03",
    domain: "api-design",
    title: "Client types come from the contract",
    rule: "Client code gets its API types from the contract, never by writing them by hand, and CI fails if they fall behind it.",
    why: "Hand-written types are a copy of the contract that silently goes out of date.",
    ask: "Does this change write any API type by hand instead of generating it from the contract?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
  {
    id: "API-04",
    domain: "api-design",
    title: "Errors have one shape",
    rule: "Every error response from the API has the same shape.",
    why: "A client that has to handle four error formats will handle three of them.",
    ask: "Does every error in this change use the API's one error shape?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "API-05",
    domain: "api-design",
    title: "Lists have one shape",
    rule: "Every list response has the same shape, everywhere in the API. The profile gives a default.",
    why: "A client can't write one list component against four conventions.",
    ask: "Does every list in this change use the API's one list shape?",
    stage: "mvp",
    check: "ai-review",
    severity: "low",
  },
  {
    id: "API-06",
    domain: "api-design",
    title: "Changing a field breaks clients: add, migrate, then remove",
    rule: "Adding a field is safe. Removing, renaming or retyping one breaks clients, so it's done in steps: add the new one, move every client across, then remove the old one.",
    why: "Clients aren't updated at the same moment as the server, and some, like installed phone apps, are never updated at all.",
    ask: "Does this change remove, rename or retype a field that clients may still use?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "API-07",
    domain: "api-design",
    title: "Every list is paged",
    rule: "Every endpoint that returns a list returns it a page at a time. None returns everything.",
    why: "An endpoint that returns everything passes every test on sample data, then falls over on real data.",
    ask: "Does every list endpoint in this change return pages?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
  {
    id: "API-08",
    domain: "api-design",
    title: "Page sizes come from one place",
    rule: "The default and largest page sizes come from one shared place, not each endpoint's own numbers.",
    why: '"What\'s the largest page a client can ask for?" should have one answer, especially under load.',
    ask: "Does this change set a page size anywhere other than the shared place?",
    stage: "mvp",
    check: "ai-review",
    severity: "low",
  },
] satisfies RuleInput[];
