import type { RuleInput } from "../rule.ts";

// How a system is divided, and which way its parts depend on each other. These hold for any
// architecture: a modular monolith, microservices, a mobile app or a library. A folder layout
// is a stack profile's default, never a core rule.

export const architecture = [
  {
    id: "ARC-01",
    domain: "architecture",
    title: "Code is judged against the project's own architecture",
    rule: "Code is judged against the architecture the project has declared (its tracks, each track's architecture and its decision records), never against a structure from somewhere else.",
    why: "A review that expects a layout the project never chose buries the real problems under false ones.",
    ask: "Does this review check the code against the architecture the project declared?",
    stage: "prototype",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "ARC-02",
    domain: "architecture",
    title: "One module owns each area",
    rule: "Each area of the business is owned by one module. Another area that needs its logic calls it; it never copies it.",
    why: "Two implementations of one business rule will disagree, and nobody will know which is right.",
    ask: "Does this change put its logic in the module that owns that area?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "ARC-03",
    domain: "architecture",
    title: "Modules don't reach into each other's internals",
    rule: "A module has a deliberate public surface, and nothing uses its internals. Something several modules need is moved somewhere shared and named honestly.",
    why: "Marking something internal tells the next person they may change it freely. Using it from elsewhere breaks that promise, and the break shows up later as someone else's bug.",
    ask: "Does anything in this change use another module's internals?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "ARC-04",
    domain: "architecture",
    title: "Business rules are plain code",
    rule: "Business rules, calculations and validation live in plain code, with no database, network, framework or user interface in it, so they can be tested with plain values.",
    why: "Rules tangled with a framework can only be tested slowly and partly. Plain rules can be tested exhaustively, which is where the hardest rules need it most.",
    ask: "Could the business logic in this change be tested without a database, a network or a user interface?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "ARC-05",
    domain: "architecture",
    title: "Business logic doesn't know how it's called",
    rule: "Business logic never deals in HTTP: no status codes, no request objects, no HTTP errors. It raises its own errors, and the layer that received the request translates them.",
    why: "Logic that knows about HTTP can't be reused by a background job, a script or a different interface.",
    ask: "Does any business logic in this change refer to HTTP?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "ARC-06",
    domain: "architecture",
    title: "Dependencies point inward",
    rule: "Code depends toward the business rules, never away from them, and features don't depend on each other.",
    why: "Without a direction, every part ends up coupled to every other, and nothing can change on its own.",
    ask: "Does any dependency in this change point outward, or from one feature to another?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
  {
    id: "ARC-07",
    domain: "architecture",
    title: "Data is reached through an interface",
    rule: "Screens and business logic reach data through an interface, never a storage engine or the network directly.",
    why: "Then changing where data lives, from local storage to an API or from one API to another, touches one place.",
    ask: "Does anything outside the data layer talk to storage or the network directly?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
  {
    id: "ARC-08",
    domain: "architecture",
    title: "There is one managed way to reach the database",
    rule: "The database is reached one managed way, so transactions and connection pooling can't be bypassed.",
    why: "Code that opens its own connection escapes the transaction it should be part of, and exhausts the connection pool under load.",
    ask: "Does anything in this change open its own database connection?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
  },
] satisfies RuleInput[];
