import type { RuleInput } from "../rule.ts";

// What makes code good in any language: naming, size, duplication, errors and types.

export const codeQuality = [
  {
    id: "CODE-01",
    domain: "code-quality",
    title: "Names say what things are",
    rule: "A name says what the thing is, in the language's own style: `amountMinor` or `amount_minor`, not `amt`; `profileId` or `profile_id`, not `pid`.",
    why: "Code is read far more often than it's written. An abbreviation saves the writer a second and costs every reader a guess.",
    ask: "Could someone new to the code understand every name in this change without asking?",
    stage: "prototype",
    check: "ai-review",
    severity: "low",
  },
  {
    id: "CODE-02",
    domain: "code-quality",
    title: "True-or-false values read as statements",
    rule: "A true-or-false value is named as a statement, such as `isPublished`, `hasError` or `canBook` (or `is_published` where the language uses snake_case).",
    why: "`published` could mean a date, a flag or a count; `isPublished` can only mean one thing.",
    ask: "Does every true-or-false value in this change read as a statement?",
    stage: "prototype",
    check: "ai-review",
    severity: "low",
  },
  {
    id: "CODE-03",
    domain: "code-quality",
    title: "Things are named the way the people using the product name them",
    rule: "Code, screens and design tokens use the words the people using the product use: a person manages notifications, not webhook config.",
    why: "When the code and the product use different words, every conversation needs a translator, and mistakes hide in the translation.",
    ask: "Do the names in this change match the words on the screen and in the requirements?",
    stage: "prototype",
    check: "ai-review",
    severity: "low",
  },
  {
    id: "CODE-04",
    domain: "code-quality",
    title: "Rule of three",
    rule: "Copy code freely once, note it the second time, and move it into one shared place the third time.",
    why: "A shared piece built too early is harder to remove than three similar ones, because everything comes to depend on it.",
    ask: "Is anything in this change repeated for the third time, or shared before it was needed?",
    stage: "mvp",
    check: "ai-review",
    severity: "low",
  },
  {
    id: "CODE-05",
    domain: "code-quality",
    title: "Rules that must never disagree are shared on the first repeat",
    rule: "Money maths, validation, permission checks and safety-critical logic are moved into one shared place the first time they're repeated, not the third.",
    why: "Two copies of a rule eventually disagree. When the rule is money, safety or who may see what, the disagreement is a wrong charge, a harmed person or a data leak.",
    ask: "Is any money, validation, permission or safety logic written more than once?",
    stage: "prototype",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "CODE-06",
    domain: "code-quality",
    title: "A deliberate copy names its twin",
    rule: "If a rule truly has to live in two places, each copy says where the other one is.",
    why: "Copies drift apart silently when nobody knows the other exists.",
    ask: "Does every deliberate copy of logic point to its twin?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "CODE-07",
    domain: "code-quality",
    title: "A function does one thing",
    rule: "A function has one reason to change.",
    why: "A function that does two things can't change one of them without risking the other, and its tests have to cover both.",
    ask: "Does each function this change touches do one thing?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "CODE-08",
    domain: "code-quality",
    title: "Comments explain why; the code explains what",
    rule: "If code needs a comment to explain what it does, it's too long or badly named. Comments that explain why are welcome.",
    why: "Comments about what code does go out of date when the code changes. The reasons behind it last.",
    ask: "Does any comment in this change explain what the code does, rather than why?",
    stage: "mvp",
    check: "ai-review",
    severity: "low",
  },
  {
    id: "CODE-09",
    domain: "code-quality",
    title: "Deep nesting becomes early returns",
    rule: "When conditions nest deeply, handle the simple cases first and return, so the main path reads straight down. Each profile sets how deep is too deep.",
    why: "Every level of nesting is one more thing a reader has to hold in mind.",
    ask: "Is any code nested more deeply than its profile allows?",
    stage: "mvp",
    check: "auto",
    severity: "low",
  },
  {
    id: "CODE-10",
    domain: "code-quality",
    title: "Size prompts a question",
    rule: "A function, component or module that grows past its profile's size limit prompts a question: is it doing two things, and what could move out? Size alone isn't a defect.",
    why: "Large units usually hide a second job, and the limit is the reminder to look for it.",
    ask: "Has anything grown past its size limit, and has someone asked whether it's doing two things?",
    stage: "mvp",
    check: "auto",
    severity: "low",
  },
  {
    id: "CODE-11",
    domain: "code-quality",
    title: "No swallowed errors",
    rule: "An error is never caught and ignored. Where ignoring one is genuinely right, such as cleanup that mustn't fail the work it cleans up after, it's logged, and the reason is written beside it.",
    why: "A swallowed error turns a loud, fixable failure into silent wrong behaviour that surfaces weeks later.",
    ask: "Is any error caught and dropped without being logged and explained?",
    stage: "prototype",
    check: "auto",
    severity: "high",
  },
  {
    id: "CODE-12",
    domain: "code-quality",
    title: "Catching every kind of error needs a reason",
    rule: "Catching every kind of error at once needs a comment saying what's expected and why it's safe to handle them all the same way.",
    why: "A catch-all also catches the bugs nobody expected, and hides them.",
    ask: "Does every catch-all in this change say what it expects and why?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
  {
    id: "CODE-13",
    domain: "code-quality",
    title: "Impossible states can't be written down",
    rule: "When something has distinct states, such as loading, failed and ready, it's one status value, not several true-or-false flags that can contradict each other.",
    why: "Three flags allow eight combinations, and most of them make no sense. One status allows only the real ones.",
    ask: "Could any combination of flags in this change describe a state that can't really happen?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "CODE-14",
    domain: "code-quality",
    title: "Types are strict",
    rule: "Where the language has types, they're strict. No escape-hatch type, such as TypeScript's `any` or Python's `Any`, where a real type exists: data of unknown shape is checked and narrowed.",
    why: "An escape-hatch type switches the checks off exactly where the data is least trusted.",
    ask: "Does this change use an escape-hatch type where a real type exists?",
    stage: "prototype",
    check: "auto",
    severity: "medium",
  },
  {
    id: "CODE-15",
    domain: "code-quality",
    title: "Edge cases are handled",
    rule: "Code gives the right answer at the edges of what it can receive: time zones and daylight saving, empty and very long input, ties and equal values, the first and last item, and zero.",
    why: "Most bugs live at the edges. The ordinary path is the one everyone tries, so it's rarely where things break.",
    ask: "Does this change give the right answer at its edges: time zones, empty or huge input, ties, first and last, and zero?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
] satisfies RuleInput[];
