import type { RuleInput } from "../rule.ts";

// Databases, migrations, stored files, and data kept on a person's device.

export const data = [
  {
    id: "DATA-01",
    domain: "data",
    title: "Migrations are the only source of truth for the database's structure",
    rule: "The database's structure comes only from migrations. Tools that shape a database straight from the code are for experiments, never for a database that matters.",
    why: "Those tools can't produce everything a migration can, such as triggers or partial indexes, and they can drop data without asking.",
    ask: "Does this change shape a real database any way other than a migration?",
    stage: "mvp",
    check: "auto",
    severity: "high",
  },
  {
    id: "DATA-02",
    domain: "data",
    title: "A model change ships with its migration",
    rule: "A change to how data is modelled ships with its migration, in the same pull request, and CI checks that they match.",
    why: "A model without its migration works on the developer's machine and fails everywhere else.",
    ask: "Does every model change in this change come with its migration?",
    stage: "mvp",
    check: "auto",
    severity: "high",
  },
  {
    id: "DATA-03",
    domain: "data",
    title: "A change to stored data never loses it",
    rule: "A migration or app update keeps existing data. Renaming or reshaping moves the data across. A table, column or storage key is removed only after its data has moved and nothing reads it: add, migrate, then remove. This includes data stored on a person's device.",
    why: "Lost data can't be fixed by the next release. It's gone, along with the trust of everyone who lost it.",
    ask: "Does this change remove, rename or reshape stored data without moving what's already there?",
    stage: "prototype",
    check: "ai-review",
    severity: "critical",
  },
  {
    id: "DATA-04",
    domain: "data",
    title: "Deleting a record deletes its files",
    rule: "When a record is deleted, the files that belong to it are deleted too.",
    why: "Orphaned files keep personal data long after the person asked for it to go, and cost money to store.",
    ask: "Does deleting a record in this change also delete its files?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
    when: ["uploads"],
  },
  {
    id: "DATA-05",
    domain: "data",
    title: "Export and import round-trip exactly",
    rule: "Where the product offers export and import, importing an export gives back exactly what was exported, and a test proves it.",
    why: "An export people can't restore from exactly is a backup that fails on the day it's needed.",
    ask: "If this change affects export or import, does a test prove they still round-trip exactly?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
] satisfies RuleInput[];
