import type { RuleInput } from "../rule.ts";

// Dependencies, the pipeline every change goes through, and how changes reach people.

const ASVS = "OWASP ASVS 5.0";
const V15 = "https://github.com/OWASP/ASVS/blob/master/5.0/en/0x24-V15-Secure-Coding-and-Architecture.md";
const MASVS = "OWASP MASVS 2.1.0";

export const delivery = [
  {
    id: "DEL-01",
    domain: "delivery",
    title: "Versions are pinned and the lockfile is committed",
    rule: 'Every dependency names the exact version that was tested, never "latest", and the lockfile is committed.',
    why: '"Whatever is newest today" isn\'t a version. A build that pulls in different code tomorrow can break, or be compromised, without anyone changing a line.',
    ask: "Does this change add a dependency without an exact version, or leave the lockfile out?",
    stage: "prototype",
    check: "auto",
    severity: "medium",
  },
  {
    id: "DEL-02",
    domain: "delivery",
    title: "A new dependency is justified",
    rule: "A new dependency comes with a reason in the pull request: what it does, why nothing already there does it, and what it brings with it.",
    why: "Every dependency is code you didn't write and have to trust, update and secure for as long as you use it.",
    ask: "Does every new dependency in this change say why it's needed?",
    stage: "mvp",
    check: "ai-review",
    severity: "low",
  },
  {
    id: "DEL-03",
    domain: "delivery",
    title: "Dependencies are watched for vulnerabilities, and each is fixed in a set time",
    rule: "Dependencies are checked for known vulnerabilities on every change and at least daily, and each vulnerability is fixed within a set time for its severity.",
    why: "Most attacks on software use vulnerabilities that were already public, in components nobody updated. New ones are published every day about code that's already running, so checking only when something changes misses them.",
    ask: "Does this change leave a dependency with a known vulnerability past its time to fix?",
    stage: "mvp",
    check: "auto",
    severity: "high",
    sources: [
      { name: ASVS, ref: "15.2.1, level 1", url: V15 },
      { name: MASVS, ref: "MASVS-CODE-3", url: "https://github.com/OWASP/masvs/blob/master/controls/MASVS-CODE-3.md" },
    ],
  },
  {
    id: "DEL-04",
    domain: "delivery",
    title: "Every change passes the same required checks before it merges",
    rule: "Every change passes the same automated checks before it merges: formatting, linting, types, tests, secret scanning, dependency checks and code scanning. The checks are required, not advisory.",
    why: "A check that can be skipped will be skipped, on the day it would have caught something.",
    ask: "Does this change merge only after passing every required check?",
    stage: "mvp",
    check: "auto",
    severity: "high",
  },
  {
    id: "DEL-05",
    domain: "delivery",
    title: "No check only reports",
    rule: "Every check in the pipeline fails the build when it finds a problem. None is set to report and carry on.",
    why: "A check that reports without failing gives the same green as a clean pass, so nobody reads it.",
    ask: "Is any check in this change set to report without failing the build?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
  {
    id: "DEL-06",
    domain: "delivery",
    title: "Changes reach production only through the pipeline",
    rule: "Changes reach production only through the pipeline, never by hand from someone's computer.",
    why: "A change made by hand skips every check, and nobody can say afterwards exactly what's running.",
    ask: "Could any change in this project reach production without going through the pipeline?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "DEL-07",
    domain: "delivery",
    title: "Only what's needed ships to production",
    rule: "Production gets only what the product needs to run: no test code, sample code, development tools or debug features.",
    why: "Every extra piece in production is something an attacker can find and use.",
    ask: "Does this change ship test, sample or development code to production?",
    stage: "production",
    check: "ai-review",
    severity: "medium",
    sources: [{ name: ASVS, ref: "15.2.3, level 2", url: V15 }],
  },
  {
    id: "DEL-08",
    domain: "delivery",
    title: "The running app is scanned before it's released",
    rule: "Before a release reaches production, a scanner tests the running app in staging from the outside, the way an attacker would. Every finding is fixed or recorded as an accepted risk. The scan runs only against the project's own staging, never production or anyone else's system.",
    why: "Code scanning reads the code. It can't see a server that's set up wrongly, a debug page left switched on or a missing security header. Only testing the running app finds those.",
    ask: "Was the running app scanned in staging before this release, and is every finding fixed or accepted?",
    stage: "production",
    check: "auto",
    severity: "medium",
  },
  {
    id: "DEL-09",
    domain: "delivery",
    title: "Packages come only from the registry you expect",
    rule: "Every dependency, and everything it depends on, is installed from the registry the project expects. A name the project uses for its own private packages can't be served from a public registry instead.",
    why: "If a private package's name is free on a public registry, anyone can publish a package under it with a higher version, and a build that looks in both places installs theirs. This is called dependency confusion.",
    ask: "Could any dependency in this change be installed from a registry the project doesn't expect?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
    sources: [
      { name: ASVS, ref: "15.2.4, level 3", url: V15 },
      { name: ASVS, ref: "15.1.2, level 2", url: V15 },
    ],
  },
  {
    id: "DEL-10",
    domain: "delivery",
    title: "There's a current list of every dependency",
    rule: "The project keeps a list of every dependency it ships, direct and indirect, with its version and where it comes from, such as a software bill of materials, and updates it with every release.",
    why: "When a vulnerability is announced, the first question is whether you use the affected package. Without a list, answering takes days; with one, it's a search.",
    ask: "Is the list of dependencies up to date for this release?",
    stage: "production",
    check: "auto",
    severity: "medium",
    sources: [{ name: ASVS, ref: "15.1.2, level 2", url: V15 }],
  },
  {
    id: "DEL-11",
    domain: "delivery",
    title: "Every dependency's licence allows how the product uses it",
    rule: "Each dependency's licence is known and allows how the product is used and distributed. A licence that would require publishing the product's own code, or that forbids commercial use, needs a person's decision before the dependency is added.",
    why: "A licence is a legal agreement. One that doesn't fit can force a product to publish its code or stop selling it, and it's cheapest to catch before the code depends on it.",
    ask: "Does this change add a dependency whose licence doesn't fit how the product is used?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "DEL-12",
    domain: "delivery",
    title: "Risky dependencies are chosen on purpose",
    rule: "A dependency that runs code when it's installed, is no longer maintained, or has a name one slip away from a better-known package is checked before it's added, and kept only with a written reason.",
    why: "Attackers take over abandoned packages and publish look-alike names, and a package that runs code when it's installed runs it on every developer's machine and every build.",
    ask: "Does this change add a dependency that runs code when installed, is no longer maintained, or looks like another package's name?",
    stage: "production",
    check: "ai-review",
    severity: "high",
    sources: [{ name: ASVS, ref: "15.1.4, level 3", url: V15 }],
  },
] satisfies RuleInput[];
