import type { RuleInput } from "../rule.ts";

// Design tokens, shared components, and making the product work for everyone. Accessibility
// rules cite the WCAG 2.2 success criterion they come from, checked against the W3C's text. The
// numbers a platform sets, such as touch target sizes, are in the stack profiles.

const WCAG = "WCAG 2.2";
const sc = (anchor: string) => `https://www.w3.org/TR/WCAG22/#${anchor}`;

export const designAccessibility = [
  {
    id: "DES-01",
    domain: "design-accessibility",
    title: "Design values come from tokens",
    rule: "Colours, spacing, corner radii and font sizes come from design tokens. None is written directly into a screen or component.",
    why: "A hard-coded value is missed by every rebrand, dark theme and accessibility fix that changes the tokens.",
    ask: "Does this change write a colour, spacing, radius or font size directly?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
  {
    id: "DES-02",
    domain: "design-accessibility",
    title: "Tokens come from one place, used by every app",
    rule: "Design tokens have one source, independent of any framework, and every app reads from it: light and dark palettes, type scale, spacing, radii and elevation.",
    why: "Two copies of the tokens drift, and the web and mobile apps stop looking like one product.",
    ask: "Does this change define design values anywhere other than the one token source?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
  {
    id: "DES-03",
    domain: "design-accessibility",
    title: "Token names say what they're for",
    rule: "Tokens are named for their purpose, such as `surface`, `accent` or `danger`, never for how they look, such as `blue500`.",
    why: "Names that describe purpose survive a rebrand and a dark theme. Names that describe a colour are wrong the day the colour changes.",
    ask: "Does any token in this change describe how it looks rather than what it's for?",
    stage: "mvp",
    check: "ai-review",
    severity: "low",
  },
  {
    id: "DES-04",
    domain: "design-accessibility",
    title: "Screens are built from the shared components",
    rule: "Screens are built only from the shared set of interface components. A screen that needs a new one adds it to the set, rather than building it inline.",
    why: "Inline one-offs are where inconsistency, missing states and accessibility gaps collect.",
    ask: "Does any screen in this change build an interface element instead of using a shared component?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
  {
    id: "DES-05",
    domain: "design-accessibility",
    title: "Every shared component comes with all its states",
    rule: "Every shared component has all its states: default, pressed, focused, disabled, loading, error and, where it applies, empty. One without them isn't finished.",
    why: "A missing state is found by a person at the worst moment: a button that looks tappable while it's still saving.",
    ask: "Does every shared component in this change have all its states?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "DES-06",
    domain: "design-accessibility",
    title: "The danger colour means one thing",
    rule: "The danger colour is kept for the one meaning the project gives it, such as money going wrong or a safety warning. It's never decoration, and never a general error.",
    why: "A signal used for everything teaches people to ignore it, including the time it matters.",
    ask: "Is the danger colour in this change used for anything but its one meaning?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "DES-07",
    domain: "design-accessibility",
    title: "Information is never shown by colour alone",
    rule: "Anything shown with colour, such as a status or an error, is also shown with text, a shape or an icon with a label.",
    why: "About one man in twelve has some colour blindness, and screen readers don't read colours at all.",
    ask: "Is any information in this change shown by colour alone?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
    sources: [{ name: WCAG, ref: "1.4.1, level A", url: sc("use-of-color") }],
  },
  {
    id: "DES-08",
    domain: "design-accessibility",
    title: "Every control has an accessible name",
    rule: "Every button, link and control has a name a screen reader can announce, including buttons that show only an icon.",
    why: 'An unlabelled control is announced as "button", and the person has no way to know what it does.',
    ask: "Does every control in this change have an accessible name?",
    stage: "prototype",
    check: "auto",
    severity: "medium",
    sources: [{ name: WCAG, ref: "4.1.2, level A", url: sc("name-role-value") }],
  },
  {
    id: "DES-09",
    domain: "design-accessibility",
    title: "Form fields have labels",
    rule: "Every form field has a visible label that stays visible while the person types. A placeholder isn't a label.",
    why: "A placeholder disappears as soon as someone types, and many screen readers don't announce it.",
    ask: "Does every form field in this change have a label, not just a placeholder?",
    stage: "prototype",
    check: "ai-review",
    severity: "medium",
    sources: [
      { name: WCAG, ref: "3.3.2, level A", url: sc("labels-or-instructions") },
      { name: WCAG, ref: "1.3.1, level A", url: sc("info-and-relationships") },
    ],
  },
  {
    id: "DES-10",
    domain: "design-accessibility",
    title: "Everything works with a keyboard",
    rule: "On the web, everything a person can do with a mouse or a tap, they can do with a keyboard alone.",
    why: "Many people can't use a mouse, and a control a keyboard can't reach locks them out of the whole task.",
    ask: "Can everything in this change be done with a keyboard alone?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
    sources: [{ name: WCAG, ref: "2.1.1, level A", url: sc("keyboard") }],
  },
  {
    id: "DES-11",
    domain: "design-accessibility",
    title: "Focus is always visible",
    rule: "The element that has keyboard focus is always clearly visible.",
    why: "Someone using a keyboard can't act on what they can't see is selected.",
    ask: "Is keyboard focus visible on everything in this change?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
    sources: [{ name: WCAG, ref: "2.4.7, level AA", url: sc("focus-visible") }],
  },
  {
    id: "DES-12",
    domain: "design-accessibility",
    title: "Dragging always has an alternative",
    rule: "Anything done by dragging can also be done without dragging, such as with buttons to move an item up or down.",
    why: "Dragging needs a steady hand and a pointer, which many people don't have.",
    ask: "Can everything this change does by dragging also be done another way?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
    sources: [{ name: WCAG, ref: "2.5.7, level AA", url: sc("dragging-movements") }],
  },
  {
    id: "DES-13",
    domain: "design-accessibility",
    title: "Contrast meets WCAG AA in every theme",
    rule: "Text, icons and control borders have enough contrast against their background in every theme: at least 4.5 to 1 for normal text.",
    why: "Low contrast is unreadable in sunlight, on cheap screens, and for many people with low vision.",
    ask: "Does every colour pair in this change meet WCAG AA contrast, in every theme?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
    sources: [
      { name: WCAG, ref: "1.4.3, level AA", url: sc("contrast-minimum") },
      { name: WCAG, ref: "1.4.11, level AA", url: sc("non-text-contrast") },
    ],
  },
  {
    id: "DES-14",
    domain: "design-accessibility",
    title: "Text follows the person's text size",
    rule: "Text grows with the person's text size setting, and the layout still works when it does.",
    why: "People who need larger text set it once, and an app that ignores it is one they can't read.",
    ask: "Does all text in this change follow the person's text size setting?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
    sources: [{ name: WCAG, ref: "1.4.4, level AA", url: sc("resize-text") }],
  },
  {
    id: "DES-15",
    domain: "design-accessibility",
    title: "Touch targets are large enough",
    rule: "Everything a person taps or clicks is large enough to hit reliably. Each platform's profile sets the size.",
    why: "Small targets cause mis-taps for everyone, and for people with tremors they make an app unusable.",
    ask: "Is every tap or click target in this change at least its platform's minimum size?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
    sources: [{ name: WCAG, ref: "2.5.8, level AA", url: sc("target-size-minimum") }],
  },
  {
    id: "DES-16",
    domain: "design-accessibility",
    title: "Animation respects the reduced-motion setting",
    rule: "Every animation that isn't essential stops or softens when the person has asked for reduced motion.",
    why: "Movement on screen can cause dizziness and nausea for people with vestibular disorders.",
    ask: "Does every animation in this change respect the reduced-motion setting?",
    stage: "mvp",
    check: "auto",
    severity: "low",
    sources: [{ name: WCAG, ref: "2.3.3, level AAA", url: sc("animation-from-interactions") }],
  },
] satisfies RuleInput[];
