import type { RuleInput } from "../rule.ts";

// How screens get, hold and show data, whatever the framework. Each stack profile says how.

const WCAG = "WCAG 2.2";
const sc = (anchor: string) => `https://www.w3.org/TR/WCAG22/#${anchor}`;

export const frontend = [
  {
    id: "FE-01",
    domain: "frontend",
    title: "Data from the server lives in one cache, not in screen state",
    rule: "Data that came from a server or a stored source is read from one shared cache, never copied into a screen's own state.",
    why: "A copy goes stale, sends duplicate requests, and races with the original when someone moves quickly between screens.",
    ask: "Does this change copy server data into a screen's own state?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "FE-02",
    domain: "frontend",
    title: "Values that follow from other data are calculated, never stored",
    rule: "Totals, counts and statuses that follow from other data are calculated when they're read, never stored alongside it.",
    why: "A stored copy of a calculated value is how two screens come to disagree.",
    ask: "Does this change store a value that could be calculated from other data?",
    stage: "prototype",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "FE-03",
    domain: "frontend",
    title: "Truly global state lives in one store; everything else stays local",
    rule: "State that the whole app shares lives in one store. Everything else stays in the component or feature that uses it.",
    why: "Global state is shared by everything, so every piece of it is a way for one part of the app to break another.",
    ask: "Is any state in this change made global when only one part of the app uses it?",
    stage: "mvp",
    check: "ai-review",
    severity: "low",
  },
  {
    id: "FE-04",
    domain: "frontend",
    title: "Values aren't passed down through layers that don't use them",
    rule: "A value is passed through only a few components that don't use it; the profile sets how many. Past that, it's fixed with composition first, then shared context, then a store.",
    why: '"No prop drilling" can\'t be enforced because nobody agrees where it starts. A number can be counted in review.',
    ask: "Does any value in this change pass through more components that don't use it than the profile allows?",
    stage: "mvp",
    check: "ai-review",
    severity: "low",
  },
  {
    id: "FE-05",
    domain: "frontend",
    title: "A component fetches data or shows it, not both",
    rule: "Data is fetched where a screen begins. Everything below it receives what it needs and only shows it.",
    why: "A component that only shows what it's given can be tested and reused without a network.",
    ask: "Does any component in this change both fetch data and show it?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "FE-06",
    domain: "frontend",
    title: "Only screens know about navigation",
    rule: "Only a screen knows how to move to another screen. Components below it receive what to do as a function.",
    why: "A component that navigates on its own can't be reused anywhere the route is different.",
    ask: "Does any component in this change, other than a screen, navigate?",
    stage: "mvp",
    check: "auto",
    severity: "low",
  },
  {
    id: "FE-07",
    domain: "frontend",
    title: "Every screen that waits handles loading, empty and error",
    rule: "Every screen or component that waits for data shows loading, empty and error states explicitly. An endless spinner is a bug.",
    why: "The happy path is the only one that gets built by default, and people meet the others first on a bad connection.",
    ask: "Does everything in this change that waits for data handle loading, empty and error?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "FE-08",
    domain: "frontend",
    title: "An error message says what happened and what to do next",
    rule: 'An error message tells the person what went wrong and what they can do about it. A bare "Something went wrong" isn\'t enough.',
    why: "A message that explains nothing leaves the person stuck, and turns into a support request.",
    ask: "Does every error message in this change say what happened and what to do next?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
    sources: [
      { name: WCAG, ref: "3.3.1, level A", url: sc("error-identification") },
      { name: WCAG, ref: "3.3.3, level AA", url: sc("error-suggestion") },
    ],
  },
  {
    id: "FE-09",
    domain: "frontend",
    title: "Offline is a state, not an error",
    rule: "With no connection, the app says so, keeps what the person did, and catches up when it's back online. Nothing typed is lost.",
    why: "People lose connection in lifts, on trains and in basements, and losing their work there teaches them not to trust the app.",
    ask: "Does this change keep working, and keep what the person did, with no connection?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
    when: ["offline"],
  },
] satisfies RuleInput[];
