import type { RuleInput } from "../rule.ts";

// For products with the money trait. The project's add-on names its currency's smallest unit.

export const money = [
  {
    id: "MONEY-01",
    domain: "money",
    title: "Money is a whole number in the currency's smallest unit",
    rule: "Money is stored and calculated as a whole number in the currency's smallest unit (pence, kobo, cents), and named for it, such as `amount_minor`. A decimal number touching money is a critical problem on sight, even for display.",
    why: "Decimal fractions can't hold most money amounts exactly. The errors are tiny, silent, and they add up.",
    ask: "Is any money held or calculated as a decimal number?",
    stage: "prototype",
    check: "auto",
    severity: "critical",
  },
  {
    id: "MONEY-02",
    domain: "money",
    title: "Each amount has one authoritative value",
    rule: "Each amount has one authoritative field. Any other copy is a mirror on its way out, and deciding anything from it is a defect, even when it gives the right answer.",
    why: "Two copies of an amount drift apart, and a decision made from the wrong one is wrong in a way nobody notices.",
    ask: "Does any decision in this change read a copy of an amount rather than its authoritative value?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "MONEY-03",
    domain: "money",
    title: "Money maths has one implementation",
    rule: "Rounding, splitting, conversion and commission each have exactly one implementation, used everywhere.",
    why: "A second implementation will disagree with the first, a penny at a time.",
    ask: "Does this change calculate money anywhere other than the one money module?",
    stage: "prototype",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "MONEY-04",
    domain: "money",
    title: "Money is formatted in one place",
    rule: "Every amount shown to a person goes through one formatting function.",
    why: "Two formatters show the same amount two ways, and people stop trusting the numbers.",
    ask: "Does this change format money anywhere other than the one formatter?",
    stage: "prototype",
    check: "auto",
    severity: "medium",
  },
  {
    id: "MONEY-05",
    domain: "money",
    title: "No money maths in the user interface",
    rule: "Totals come from the server or from tested money code, never from arithmetic in a screen.",
    why: "Maths in a screen is untested, and a screen that shows a different total from the receipt is a support call at best.",
    ask: "Does any screen or component in this change do arithmetic on money?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "MONEY-06",
    domain: "money",
    title: "A money movement is never negative; its direction is a type",
    rule: "A money movement's amount is always positive, and its direction is a named type: income, expense, transfer, payment, refund. A balance can be negative.",
    why: "A minus sign is easy to lose or to double, and a lost sign sends money the wrong way.",
    ask: "Does any money movement in this change carry its direction in its sign?",
    stage: "mvp",
    check: "auto",
    severity: "high",
  },
  {
    id: "MONEY-07",
    domain: "money",
    title: "The books balance",
    rule: "Every ledger entry has its counterpart, and any change to how entries are posted comes with a test that proves the books still balance.",
    why: "An unbalanced ledger means money has appeared or vanished, and finding where takes far longer than preventing it.",
    ask: "If this change affects ledger entries, does a test prove the books still balance?",
    stage: "mvp",
    check: "ai-review",
    severity: "critical",
  },
  {
    id: "MONEY-08",
    domain: "money",
    title: "Anything that moves money is safe to repeat",
    rule: "A request, job or webhook that moves money can run twice without moving it twice. It's keyed on something the caller supplies, never on timing, and every API that creates or moves money accepts an idempotency key.",
    why: "Phones retry on patchy connections, people double-tap, and queues redeliver. Repeats are normal, not rare.",
    ask: "What happens if this money operation runs twice?",
    stage: "mvp",
    check: "ai-review",
    severity: "critical",
  },
  {
    id: "MONEY-09",
    domain: "money",
    title: "A payment provider's webhook is verified before it does anything",
    rule: "A webhook's signature is verified before it has any effect, and an event already seen is ignored.",
    why: "Anyone can send a request that looks like a payment notification, and a replayed one can credit money twice.",
    ask: "Is this webhook's signature verified before anything happens, and are replays ignored?",
    stage: "mvp",
    check: "ai-review",
    severity: "critical",
  },
  {
    id: "MONEY-10",
    domain: "money",
    title: "Every money path is tested for its amounts",
    rule: "Every path that calculates or moves money has a test that checks the amounts, not just that the request succeeded.",
    why: "A money bug that returns a success is the most expensive kind: it looks fine until the books are reconciled.",
    ask: "Does every money path in this change have a test that checks the amounts?",
    stage: "mvp",
    check: "auto",
    severity: "high",
  },
  {
    id: "MONEY-11",
    domain: "money",
    title: "Money moving is visible",
    rule: "Money movements emit a metric, so a person can see whether money is moving normally right now without querying the database by hand.",
    why: "When payments quietly stop, every minute of not knowing costs real money and real trust.",
    ask: "Would a sudden change in money movements show up on a dashboard or an alert?",
    stage: "production",
    check: "ai-review",
    severity: "medium",
  },
] satisfies RuleInput[];
