import type { RuleInput } from "../rule.ts";

// Environments, access to production, backups, logs, metrics and alerts. Keeping environments
// apart and controlling access to production are what audits such as PCI DSS and ISO 27001 check;
// Peer AI grades them by stage so a prototype isn't held to production's bar.

export const operations = [
  {
    id: "OPS-01",
    domain: "operations",
    title: "Development and production are kept apart",
    rule: "Development and test never share production's servers, databases or secrets: each environment has its own, so a mistake while building can't touch real customers.",
    why: "A test run against the production database, or a development machine holding production's secrets, is how real data gets deleted or leaked. Audits such as PCI DSS and ISO 27001 check for this separation.",
    ask: "Does anything in this change share a server, database or secret between development and production?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "OPS-02",
    domain: "operations",
    title: "Real people's data never goes into development or test",
    rule: "Development and test use made-up data, or copies of production where personal data has been anonymised or replaced. A plain copy of production is never used for testing.",
    why: "A copy of production puts real people's data somewhere less protected, where more people can see it. Data protection laws treat that as a breach waiting to happen, and PCI DSS forbids real card numbers in test outright.",
    ask: "Does this change put real people's data into development or test?",
    stage: "prototype",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "OPS-03",
    domain: "operations",
    title: "Nobody has everyday access to production",
    rule: "Developers have no standing access to production. When someone truly needs it, such as during an outage, it's approved, time-limited and recorded.",
    why: "Standing access means one stolen laptop or one mistyped command reaches production. Access that's approved and recorded can be explained afterwards.",
    ask: "Who has access to production today, and is every use approved, time-limited and recorded?",
    stage: "production",
    check: "person",
    severity: "high",
  },
  {
    id: "OPS-04",
    domain: "operations",
    title: "A staging environment mirrors production",
    rule: "A staging environment is set up like production, with anonymised data, and every change passes through it before it reaches production.",
    why: '"It worked on my machine" is what staging exists to catch, before real customers find it instead.',
    ask: "Does this change pass through a staging environment that mirrors production?",
    stage: "production",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "OPS-05",
    domain: "operations",
    title: "Backups are automatic",
    rule: "Data is backed up automatically, at least daily, to somewhere separate from where it lives.",
    why: "The backup you meant to set up is the one you need on the day the database is lost.",
    ask: "Is the data in this change backed up automatically, somewhere separate?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "OPS-06",
    domain: "operations",
    title: "Restores are tested, and redundancy matches the uptime target",
    rule: "Restoring from backup is tested on a schedule, and the system has enough redundancy to meet the uptime it promises.",
    why: "A backup that has never been restored is a hope, not a backup.",
    ask: "When was a restore from backup last tested, and does the redundancy match the uptime target?",
    stage: "production",
    check: "person",
    severity: "medium",
  },
  {
    id: "OPS-07",
    domain: "operations",
    title: "Logs are structured",
    rule: "Logs are written as structured fields, not sentences built by pasting values together.",
    why: "Structured logs can be searched and counted during an incident. Pasted-together text can't, and it's where secrets slip in.",
    ask: "Does this change write any log line by pasting values into text?",
    stage: "mvp",
    check: "auto",
    severity: "low",
  },
  {
    id: "OPS-08",
    domain: "operations",
    title: "Every request can be traced end to end",
    rule: "Each request carries one id, which appears in its log lines, its trace and the error the client sees.",
    why: "When a customer reports an error, the id takes you straight to what happened instead of hours of searching.",
    ask: "Can every request in this change be traced by one id from the client's error to the logs?",
    stage: "production",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "OPS-09",
    domain: "operations",
    title: "An alert fires only on something a person would act on",
    rule: "Every alert is about something a person needs to act on, and says what to do.",
    why: "Alerts that don't need action teach people to ignore alerts, including the one that matters.",
    ask: "Does every alert in this change need a person to act?",
    stage: "production",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "OPS-10",
    domain: "operations",
    title: "Health checks are cheap and honest",
    rule: "Health and readiness checks are cheap to run and tell the truth: ready means able to serve requests, not just that the process started.",
    why: "A readiness check that always says yes sends traffic to a server that can't handle it.",
    ask: "Do the health checks in this change say whether the service can really serve requests?",
    stage: "production",
    check: "ai-review",
    severity: "medium",
  },
] satisfies RuleInput[];
