import type { RuleInput } from "../rule.ts";

// Staying up, and failing safely when something underneath fails.

export const reliability = [
  {
    id: "REL-01",
    domain: "reliability",
    title: "Every call to another service has a timeout and handles failure",
    rule: "Every call to another service or API has a timeout, and a failed or slow response is handled: retried when that's safe, reported when it isn't.",
    why: "A call with no timeout waits forever, and one slow provider then ties up every request that depends on it.",
    ask: "Does every call to another service in this change have a timeout and handle failure?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "REL-02",
    domain: "reliability",
    title: "If the cache is down, requests are slower, not failed",
    rule: "When a cache is unavailable, requests fall back to working without it. They get slower; they don't fail.",
    why: "A cache is there to speed things up. If losing it takes the service down, it has become a single point of failure.",
    ask: "Does everything in this change keep working if the cache is down?",
    stage: "production",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "REL-03",
    domain: "reliability",
    title: "Rate limiting never switches off",
    rule: "If the rate limiter's shared store is down, it falls back to a limit on each server and raises an alert. For sign-in, password reset, two-factor and one-time codes, the fallback is at least as strict as normal. Limiting is never simply switched off.",
    why: "Refusing every request would turn a cache outage into a total outage, and allowing unlimited sign-in attempts would open a window for guessing passwords.",
    ask: "If the rate limiter's store fails, does this change still limit requests, as strictly for sign-in?",
    stage: "production",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "REL-04",
    domain: "reliability",
    title: "Configuration fails closed",
    rule: "An unrecognised environment name is treated as production, and one function decides which environment is running.",
    why: "A typo in an environment name must never switch production's safeguards off.",
    ask: "Does this change decide the environment anywhere other than the one function, or treat an unknown one as safe?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "REL-05",
    domain: "reliability",
    title: "Demo shortcuts can't run in production",
    rule: "Demo passwords, seed shortcuts and sandbox providers are refused when the app starts in production.",
    why: "A convenience left switched on in production is a back door.",
    ask: "Could any demo or test shortcut in this change run in production?",
    stage: "production",
    check: "auto",
    severity: "high",
  },
  {
    id: "REL-06",
    domain: "reliability",
    title: "Every process runs the same safety checks at start-up",
    rule: "Every process that can move money or change data, including background workers and scripts, runs the same production safety checks when it starts as the main server.",
    why: "The worker nobody thought about is the one that runs with the unsafe setting.",
    ask: "Does every process in this change run the same start-up safety checks as the server?",
    stage: "production",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "REL-07",
    domain: "reliability",
    title: "A dropped live connection loses nothing that mattered",
    rule: "Anything that matters is saved, not held only in a live connection, so a dropped connection loses nothing.",
    why: "Live connections drop all the time on mobile networks. State that only existed in the stream is gone.",
    ask: "Would a dropped connection lose anything that matters in this change?",
    stage: "production",
    check: "ai-review",
    severity: "medium",
    when: ["real-time"],
  },
  {
    id: "REL-08",
    domain: "reliability",
    title: "When the device holds the only copy, it's protected",
    rule: "When a person's device holds the only copy of their data, the app asks the platform to keep it rather than clear it when space runs short, and offers a way to back it up.",
    why: "Browsers and phones clear stored data under pressure, and for an offline-first app that can mean everything the person ever entered.",
    ask: "Is data that exists only on the device protected from being cleared, with a way to back it up?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
    when: ["offline"],
  },
  {
    id: "REL-09",
    domain: "reliability",
    title: "An app that caches itself still updates",
    rule: "An app that caches its own code to work offline checks for new versions and applies them, so every person gets updates.",
    why: "An app that always serves its cached copy never gets fixes, including the fix for the bug that's hurting people.",
    ask: "Will people running a cached copy of this app get the next version?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
    when: ["offline"],
  },
] satisfies RuleInput[];
