import type { RuleInput } from "../rule.ts";

// How the system behaves under load, concurrency and background work.

export const systemDesign = [
  {
    id: "SYS-01",
    domain: "system-design",
    title: "Background jobs are safe to run twice",
    rule: "A background job gives the same result if it runs twice, because queues redeliver.",
    why: "A job that assumes it runs exactly once corrupts data the first time a queue redelivers it.",
    ask: "What happens if a job in this change runs twice?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "SYS-02",
    domain: "system-design",
    title: "Nothing slow blocks a request",
    rule: "Slow work such as sending email, push notifications and processing documents goes to a queue. A request never waits for it.",
    why: "A confirmation that waits on a mail server fails whenever the mail server is slow.",
    ask: "Does any request in this change wait for slow work that could go to a queue?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "SYS-03",
    domain: "system-design",
    title: "Two people will do the same thing at the same time",
    rule: "If two people doing the same thing at once could corrupt data, the database prevents it, not the order the code happens to run in. Counting rows and adding one is not a way to make ids.",
    why: "Two checkouts on the last slot, or two couriers accepting one job, happen every day under real load.",
    ask: "What happens if two people run this change's code at the same moment?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "SYS-04",
    domain: "system-design",
    title: "What's read to be changed is locked first",
    rule: "Reading a value, changing it and writing it back, such as a balance or a count of places left, locks the record while it happens, using one shared lock helper.",
    why: "Without the lock, two changes read the same value and one of them is silently lost.",
    ask: "Does any read, change and write in this change lock what it's changing?",
    stage: "mvp",
    check: "ai-review",
    severity: "high",
  },
  {
    id: "SYS-05",
    domain: "system-design",
    title: "A database guarantee beats a check in code",
    rule: "Where a rule can be a database guarantee, such as a unique constraint, it is one, rather than a check in the code.",
    why: "\"Check that it doesn't exist, then insert\" can be raced. A unique constraint can't.",
    ask: "Does this change check a rule in code that the database could guarantee?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "SYS-06",
    domain: "system-design",
    title: "Contested state is tested concurrently",
    rule: "Anything with limited capacity, held money or payouts has a test that runs it concurrently.",
    why: "A test that runs one step at a time can't find the bug that only happens when two run at once.",
    ask: "Does this change to contested state come with a test that runs it concurrently?",
    stage: "production",
    check: "ai-review",
    severity: "medium",
  },
] satisfies RuleInput[];
