import type { RuleInput } from "../rule.ts";

// What's tested, and how tests stay trustworthy.

export const testing = [
  {
    id: "TEST-01",
    domain: "testing",
    title: "A bug fix ships with the test that would have caught it",
    rule: "Every bug fix comes with a test that fails without the fix and passes with it.",
    why: "A bug fixed without a test comes back, usually during the next refactor.",
    ask: "Does this bug fix come with a test that would have caught the bug?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "TEST-02",
    domain: "testing",
    title: "The main journeys are the acceptance tests",
    rule: "The main journeys through the product are written as end-to-end tests, and an area isn't done until they pass. A rebuild must pass the old product's journeys.",
    why: "Unit tests can all pass while the one thing people came to do is broken.",
    ask: "Do the product's main journeys still pass with this change?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
  {
    id: "TEST-03",
    domain: "testing",
    title: "Business rules are tested thoroughly with plain values",
    rule: "Business rules are tested with plain values, case by case, including the edges, with a name for each case.",
    why: "Plain rules are cheap to test exhaustively, and the edges are where the bugs are.",
    ask: "Are the business rules in this change tested case by case, including the edges?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
  {
    id: "TEST-04",
    domain: "testing",
    title: "Tests check behaviour, not implementation",
    rule: "Tests check what the code does, the way a person or caller would see it, not how it does it internally.",
    why: "Tests tied to the implementation break on every refactor and still miss the behaviour that matters.",
    ask: "Do the tests in this change check behaviour rather than internal details?",
    stage: "mvp",
    check: "ai-review",
    severity: "low",
  },
  {
    id: "TEST-05",
    domain: "testing",
    title: "Tests state what they need",
    rule: "A test that needs something, such as seeded data, a port or a clock, checks for it and skips with a reason when it's missing, rather than failing for want of it.",
    why: "A test that fails for the wrong reason teaches people to ignore failing tests.",
    ask: "Does every test in this change state what it needs?",
    stage: "mvp",
    check: "ai-review",
    severity: "low",
  },
  {
    id: "TEST-06",
    domain: "testing",
    title: "Test databases are built by the migrations",
    rule: "The database a test runs against is built by the same migrations as production.",
    why: "A test database built any other way passes tests that production would fail.",
    ask: "Is the test database in this change built by the migrations?",
    stage: "mvp",
    check: "auto",
    severity: "medium",
  },
  {
    id: "TEST-07",
    domain: "testing",
    title: "No test depends on another's leftovers",
    rule: "Every test sets up what it needs and cleans up after itself. None depends on what another test left behind.",
    why: "Tests that share leftovers pass or fail depending on the order they run in.",
    ask: "Could any test in this change pass or fail depending on another test?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "TEST-08",
    domain: "testing",
    title: "Security-sensitive endpoints have abuse tests",
    rule: "Endpoints that handle sign-in, permissions, money or input that reaches a database have tests that send malicious input, such as injection attempts and other people's ids, and check it's rejected. They run against the project's own app, never a live system.",
    why: "Security holes don't show up in tests that only send what a well-behaved client would send.",
    ask: "Do the security-sensitive endpoints in this change have tests that send malicious input?",
    stage: "mvp",
    check: "ai-review",
    severity: "medium",
  },
  {
    id: "TEST-09",
    domain: "testing",
    title: "A check is seen failing before it's trusted",
    rule: "A new test, lint rule or gate is made to fail once on purpose, to prove it can, before anyone relies on it passing.",
    why: "A check that can't fail reports the same green as one that passed. A green run proves nothing until you've seen it go red.",
    ask: "Has each new check in this change been seen to fail?",
    stage: "mvp",
    check: "ai-review",
    severity: "low",
  },
] satisfies RuleInput[];
