// Builds packages/peer-ai/src/v0-fingerprints.ts: for every file in every version of v0, the
// playbook Peer AI was before 1.0, its path and a fingerprint of its content (RFC 0008). peer-ai
// migrate uses it to tell v0's own files, which it can delete, from a project's edits, which it
// can't. It holds no text, only fingerprints. v0 won't change again, so this runs once, from a
// maintainer's clone of v0's history:
//
//     node scripts/v0-fingerprints.ts <v0 repository> [<repository>@<ref> ...]
//
// Every commit on every branch of the first repository is read. Each extra <repository>@<ref>
// adds one more version, such as this repository's v0.1.0 tag.

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { fingerprint } from "../packages/peer-ai/src/v0.ts";

const OUT = fileURLToPath(new URL("../packages/peer-ai/src/v0-fingerprints.ts", import.meta.url));

const git = (repo: string, args: string[]) =>
  execFileSync("git", ["-C", repo, ...args], { encoding: "buffer", maxBuffer: 64 * 1024 * 1024 });
const text = (repo: string, args: string[]) => git(repo, args).toString("utf8").trim();

const [v0, ...extra] = process.argv.slice(2);
if (v0 === undefined) {
  console.error("Usage: node scripts/v0-fingerprints.ts <v0 repository> [<repository>@<ref> ...]");
  process.exit(2);
}

const sources = [
  ...text(v0, ["rev-list", "--all"])
    .split("\n")
    .map((commit) => ({ repo: v0, ref: commit })),
  ...extra.map((spec) => {
    const at = spec.lastIndexOf("@");
    return { repo: spec.slice(0, at), ref: spec.slice(at + 1) };
  }),
];

interface Version {
  commit: string;
  date: string;
  /** Seconds since 1970, to order versions made on the same day. */
  time: number;
  files: Map<string, string>;
}

const blobs = new Map<string, string>();
const versions: Version[] = sources.map(({ repo, ref }) => {
  const commit = text(repo, ["rev-parse", "--short=7", `${ref}^{commit}`]);
  const [date = "", time = "0"] = text(repo, ["show", "-s", "--format=%cs %ct", commit]).split(" ");
  const files = new Map<string, string>();
  for (const line of text(repo, ["ls-tree", "-r", commit]).split("\n")) {
    const match = /^\d+ blob ([0-9a-f]+)\t(.+)$/.exec(line);
    if (match?.[1] === undefined || match[2] === undefined) continue;
    const blob = match[1];
    if (!blobs.has(blob)) blobs.set(blob, fingerprint(git(repo, ["cat-file", "blob", blob])));
    files.set(match[2], blobs.get(blob) ?? "");
  }
  return { commit, date, time: Number(time), files };
});
versions.sort((a, b) => a.time - b.time || a.commit.localeCompare(b.commit));

const files: Record<string, Record<string, number[]>> = {};
versions.forEach((version, index) => {
  for (const [path, hash] of version.files) {
    const byHash = (files[path] ??= {});
    (byHash[hash] ??= []).push(index);
  }
});
const sorted = Object.fromEntries(Object.entries(files).sort(([a], [b]) => a.localeCompare(b)));

writeFileSync(
  OUT,
  [
    "// Generated by scripts/v0-fingerprints.ts from v0's history. Don't edit it by hand.",
    "// For each v0 file: its fingerprints, each with the versions that had it (RFC 0008).",
    "",
    `export const V0_VERSIONS: { commit: string; date: string }[] = ${JSON.stringify(
      versions.map(({ commit, date }) => ({ commit, date })),
    )};`,
    "",
    `export const V0_FILES: Record<string, Record<string, number[]>> = ${JSON.stringify(sorted)};`,
    "",
  ].join("\n"),
);
console.log(
  `Wrote ${String(versions.length)} versions and ${String(Object.keys(sorted).length)} paths to packages/peer-ai/src/v0-fingerprints.ts.`,
);
